### ISSUE TITLE
Is there any way to disable "swipe to open" but not swipe to close?

### ISSUE THREAD

**Issue by aslamdoctor** [Mango/slideout#100]
The thing is, I am using jquery slick carousel plugin which allows to swipe left/right to move carousel slides. But slideout's swipe from left event overrides it. So I want to disable swipe from left to open the menu. But would like to leave the swipe to right enabled, to close the menu. Is it possible?

**Comment by montogeek** [comment]
I am afraid that is not possible atm, still, you can use the `touch` option to disable touch events.
`touch: false`

**Comment by aslamdoctor** [comment]
OK, thanks for the quick reply. Any chance to get that feature in future?

**Comment by pazguille** [comment]
Hi @aslamdoctor!

You can do that using the current API. You should use the `open` and `close` events.

```js
// Create a new instance with touch disabled
var slideout = new Slideout({
  'panel': document.getElementById('main'),
  'menu': document.getElementById('menu'),
  'touch': false
});

// Then, use the slideout `open` and `close` events
slideout.once('open', slideout._initTouchEvents);
slideout.on('open', slideout.enableTouch);
slideout.on('close', slideout.disableTouch);
```
Demo: http://codepen.io/anon/pen/WvavzZ
