### ISSUE TITLE
Panel option should be able to process arrays

### ISSUE THREAD

**Issue by arekkas** [Mango/slideout#106]
Currently, the panel option requires *one* HTMLElement. But there are often use cases, where you might have a more complex DOM-Tree:

```html
<body>
<nav class="slideout sidebar">/*..*/</nav>
<header>/*..*/</header>
<div class="container">/*..*/</div>
<footer>/*..*/</footer>
</body>
```

in this case, defining only one HTMLElement as a panel is not sufficient.

**Comment by montogeek** [comment]
You can wrapper them.
