### ISSUE TITLE
Menu should use transform as well

### ISSUE THREAD

**Issue by arekkas** [Mango/slideout#107]
Currently, the slide menu has `z-index: 0` and the panel has `z-index: 1`. Why isn't the slide menu using translate instead? This would remove the need for z-indexes, which get messy really quick. 

Also with z-index, transparent backgrounds are a problem:

![buggy](https://cloud.githubusercontent.com/assets/3372410/8968764/9fe9084e-363f-11e5-81a0-138e62c26770.PNG)

**Comment by arekkas** [comment]
An exemplary implementation can be found here: https://github.com/ory-am/editor/blob/toolbar-refactor/src/app/libs/slideout.js#L173-L174

This also scales down the content area (by using margin-right), which m ight not always work or be desired.

The css also changed a little: https://github.com/ory-am/editor/blob/toolbar-refactor/src/assets/sass/_toolbar.scss#L9

![slideout](https://cloud.githubusercontent.com/assets/3372410/8978045/d5a18d58-369e-11e5-943f-bef90d55adbc.gif)

**Comment by arekkas** [comment]
If you're interested in a PR let me know

**Comment by ncri** [comment]
Your links are broken....

**Comment by arekkas** [comment]
Sorry, branch was pruned

https://github.com/ory-am/editor/blob/master/src/app/libs/slideout.js#L184-L185
https://github.com/ory-am/editor/blob/master/src/assets/sass/_toolbar.scss#L9

**Comment by arekkas** [comment]
It works fine in FireFox btw but has some issues in chrome, so probably not yet suitable for a pr

**Comment by ncri** [comment]
Oh funny, yeah, i did exactly the same change and was wondering why translate3d is used. Is there any meaning? Clearly its a simple 2d translate...

**Comment by Maiti** [comment]
Great plagin!
Your links are broken.... +1
is it real a scaled content?

**Comment by Nexonion** [comment]
Please lay out an example once again, broken links.

**Comment by arekkas** [comment]
sorry, I don't have them any more. you will have to search the git history.

**Comment by pazguille** [comment]
Hi, to solve this issue you should use `min-height: 100vh;` on `.slideout-panel`.
