### ISSUE TITLE
Fixed button

### ISSUE THREAD

**Issue by ppollo07** [Mango/slideout#108]
Hello, when i use fixed header with button for open and scroll the mobile page, click the button menu, show the menu but scrolling the top.

**Comment by montogeek** [comment]
Can you please provide an example?

**Comment by ppollo07** [comment]
http://branch2.sandboxmap.com/places
emulate iphone in google chrome then scroll down and touch menu.
menu show but body scroll go top

**Comment by pazguille** [comment]
Hi @ppollo07!

You should remove `min-height:100%` and `height:100%` declarations from the `html` element in your CSS. 

See: https://github.com/Mango/slideout/issues/5#issuecomment-77687903

I made an example with a fixed element: http://codepen.io/anon/pen/YXpRBX

**Comment by ppollo07** [comment]
Thx, but my problem is an other see next example: http://codepen.io/ppollo07/pen/yNwyWd
scroll down de page, menu its fixed, click on menu, menu its open but the button go to the top of page.
you understand me?

**Comment by pazguille** [comment]
Ahhh ok. The issue is that you have an element with `position: fixed;` inside of an element that has `overflow: hidden;` See: https://miketaylr.com/posts/2015/06/position-fixed-overflow-hidden.html


I'm going to try to fix this.

**Comment by pazguille** [comment]
@ppollo07 check it out: http://codepen.io/anon/pen/NqJGBp
