### ISSUE TITLE
don't set overflow:hidden for body , it doesn't work well on android

### ISSUE THREAD

**Issue by blinkcat** [Mango/slideout#109]
I can scroll  main content of page , when menu is open.   I advise to wrap nav and main in a div, then, set overflow:hidden for this div.

**Comment by pazguille** [comment]
Hi @blinkcat,
The idea was prevent the scrolling when menu is open.
Could you make an example to add in our docs?

**Comment by xstortionist** [comment]
Wrapping nav and main in a div will create some unwanted issues for users looking to have fixed headers.

Probably best to set overflow hidden on HTML tag rather then Body for android devices.
