### ISSUE TITLE
touch option cannot be enabled after plugin init

### ISSUE THREAD

**Issue by janwidmer** [Mango/slideout#113]
Hi,

I used the slideout plugin on my project and i really like the smooth slide effect. On My Project, one requirement is, to only enable touch, when the menu is open. For that I wanted to disabled the touch option on init and later enable it with the method `slideout.enableTouch();`

That does not seem to work. Initializing the plugin with touch: false makes it being disabled forever. Using the method `slideout.enableTouch()` afterwards does not seem to do anything.

See example in JS fiddle: http://jsfiddle.net/mt7bp04p/

I made a workaround by enabling it on init, then calling the method `slideout.disableTouch()` right after initializing and that seems to work. Still it seems like a bug to me.

Thanks for your efforts.
Jan

**Comment by impronunciable** [comment]
It is a bug. After merging the `destroy` method (there is already a pull request for that) I'll decouple so the `_initTouchEvents` will have a counterpart called `_destroyTouchEvents` and fixing the bug. Thanks for reporting.

**Comment by janwidmer** [comment]
ok cool

**Comment by FlorianKoerner** [comment]
Same problem here

**Comment by pazguille** [comment]
#114
