### ISSUE TITLE
Two sidebar menus

### ISSUE THREAD

**Issue by dannyk08** [Mango/slideout#116]
At the moment I figured out how to make slideout work for both right and left sidebar menus without changing the structure of my app. 

The problem is that when I try to activate both sidebars so that there is a left and right.. The js/css breaks.. Is there a way to have both?

Thanks in advance

**Comment by dannyk08** [comment]
I figured out how to do it.. you have to declare a new Slideout


```coffee
#coffeescript

left_slideout = new Slideout(
  #options for left sidebar/slideout
)

right_slideout = new Slideout(
  #options for right sidebar/slideout
)
```

**Comment by Zaanmedia** [comment]
Do you have a working demo of 2 sidebars left and right? Can you please share what you did to make it work?

**Comment by backlashsid** [comment]
^^ that would be helpful. Please share.

**Comment by dannyk08** [comment]
@backlashsid @Zaanmedia https://github.com/dannyk08/double-slideouts

Excuse the extreme delay.. I kept forgetting to do this. Let me know if this works for you. Hope it helps others as well

**Comment by chiscojfr** [comment]
Thanks for the demo @dannyk08  it works great!

**Comment by dannyk08** [comment]
glad it helps @chiscojfr !
