### ISSUE TITLE
New release (0.1.10) to npm

### ISSUE THREAD

**Issue by kentmw** [Mango/slideout#118]
I've been using slideout (pulled from npm) and it has been working great. I would like to use the enable/disable touch methods but it seems it hasn't been released yet. What is the schedule for that?

**Comment by impronunciable** [comment]
We'll do it in the next days. If we don't, please let us know.

**Comment by kentmw** [comment]
@impronunciable, friendly reminder.

**Comment by impronunciable** [comment]
@kentmw thanks!

@pazguille I saw you merged the 'destroy' method. Do you think is a good time to do the npm deploy?

**Comment by pazguille** [comment]
Done!
