### ISSUE TITLE
Specify translate3d unit

### ISSUE THREAD

**Issue by niallobrien** [Mango/slideout#119]
It'd be really useful if you could specify the unit to use for `translate3d` via the options object, as `px` isn't always ideal for responsive design, thanks.

**Comment by m-hagberg** [comment]
This would be perfect. I for example would like to use `vw`, since I'm only using Slideout on mobile screens. Other usable units would be `%`, `em`, `rem`, and perhaps also `ex`, `vmin`, and `vmax`.

**Comment by Aaaaaashu** [comment]
+1

**Comment by Metacowboy** [comment]
+1

**Comment by Aaaaaashu** [comment]
I find a interesting method to resolve rem unit, 
just use html font-size ` 'padding': 5 * parseInt($('html').css('font-size'))`

**Comment by JoMas971** [comment]
I've done this in my branch and submit a PR #166. Hope it will be merged soon.

**Comment by niallobrien** [comment]
I'm going to close this issue and push for #166 to be merged. Thanks all.
