### ISSUE TITLE
Adding scroll event listener on window doesn't trigger events

### ISSUE THREAD

**Issue by kentmw** [Mango/slideout#124]
I added:
```
window.addEventListener('scroll', function() {console.log('scrolling');});
```
and no logs were done.

This happens on the demo webpage as well: https://mango.github.io/slideout/

**Comment by kentmw** [comment]
It looks like you can add listeners to the menu element itself. Maybe I missed it, but it might be good to give a heads up in the documentation that scroll events happen on the element, not the window.

**Comment by pazguille** [comment]
It works fine for me. I'll need more information to reproduce this issue.

**Comment by kentmw** [comment]
Go to:  https://mango.github.io/slideout/
Open Console.
Type: ```window.addEventListener('scroll', function() {console.log('scrolling');});```
Resize screen so the menu will scroll.
Open Menu
Scroll menu

It doesn't print out scrolling. That's because it's listening to the window for scrolling, not the menu element. It's pretty straight forward but I didn't understand that elements can scroll and not trigger scroll events on the window.

All in all, not a big deal, BUT lots of infinite scrolling libraries listen for scroll on the window and therefore don't work out of the box with scrolling on the menu.
