### ISSUE TITLE
Add will-change property to transitions

### ISSUE THREAD

**Issue by montogeek** [Mango/slideout#125]
Hi!

It would be great to make some performance improvements by using the will-change CSS property.

**Comment by pazguille** [comment]
https://github.com/Mango/slideout/commit/fbb35b172a0a94b3e58eb5483a14b60bacd84248

**Comment by montogeek** [comment]
NOICE

**Comment by impronunciable** [comment]
It seems that is not a good idea to use will-change on a generic case if the website is performing well. https://developer.mozilla.org/en/docs/Web/CSS/will-change (summary section). It also says it's a good idea to toggle the property before and after translation occur.

**Comment by garygreen** [comment]
I know this change was made years ago, but this change is having a major impact on content inside the `.slide-panel` - essentially it interferes with transforms inside your slideout panel. You can see this problem demonstrated here (it interferes with Sortable libraries, etc): 

https://codesandbox.io/s/l2qjjxn5kl
Demo: https://l2qjjxn5kl.codesandbox.io/

(Problem is only when your on mobile / or emulating mobile in F12 Dev Tools)

If you remove the `will-change` from the `.slideout-panel` and try drag sorting it works again.

As mentioned on mdn docs, `will-change` should be used AS A LAST RESORT and be immediately removed after mutations have occured. It should not used to prematurely optimise.
