### ISSUE TITLE
How to remove MOCHA?

### ISSUE THREAD

**Issue by shartazh** [Mango/slideout#129]
Hello!
How can I remove Mocha? When I try do it, I have separation the sidebar during opening and closing.

![First](http://don.ucoz.ru/git/1.png)
![Second](http://don.ucoz.ru/git/2.png)
![Third](http://don.ucoz.ru/git/3.png)
![Fourth](http://don.ucoz.ru/git/4.png)

**Comment by pazguille** [comment]
Hi @shartazh!

Why do you want to remove mocha? I don't understand your question.

**Comment by shartazh** [comment]
I want to use the default template without big changes like your [example](https://mango.github.io/slideout/)

**Comment by pazguille** [comment]
You could set  `min-height` property to `.slideout-panel`:

```css
.slideout-panel {
  min-height:1000px;
}
```

**Comment by shartazh** [comment]
Thank you! So much!
