### ISSUE TITLE
Android 2.2+ Support

### ISSUE THREAD

**Issue by arcxyz** [Mango/slideout#13]
It looks like a CSS error. Probably related with the position fixed of the menu
![slideoutjs](https://cloud.githubusercontent.com/assets/185002/6504909/9c51557c-c33c-11e4-9da9-9dab61db4169.gif)

**Comment by arcxyz** [comment]
Some workarounds for fixed positions:

http://bradfrost.com/blog/mobile/fixed-position/

**Comment by pazguille** [comment]
Your browser doesn't support `linear-gradient`. I'm going to add a  background-color as fallback.

**Comment by pazguille** [comment]
Could you test it? => https://mango.github.io/slideout/

**Comment by arcxyz** [comment]
It works! But the **"overflow-y: auto"** on the menu doesn't seem to be working. It is not possible to scroll 
![slideoutjs](https://cloud.githubusercontent.com/assets/185002/6505324/309b8a0a-c341-11e4-82ed-7437eef04aef.gif)

**Comment by anderskleve** [comment]
Some mobile browser don't properly support overflow. Check out the following responsive tables implementation in Zurb Foundation, and you will find the same behaviour. http://zurb.com/playground/projects/responsive-tables/index.html

You could probably use Overthrow as a polyfill if you need backwards compatibility. https://github.com/filamentgroup/Overthrow
