### ISSUE TITLE
Page does not slide over the menu

### ISSUE THREAD

**Issue by derwaldgeist** [Mango/slideout#131]
If I use the Slide.js demo page, everything works correctly.

But in my Meteor application, the page is always *under* the slideout menu, not over it. So the slide effect does not look nicely. The HTML code looks exactly like in the samples.

Is seems as if the z-index setting is ignored, by both Chrome and Safari.

What may cause this behaviour?

**Comment by derwaldgeist** [comment]
My fault, the panel did not have a background set.

**Comment by williamknn** [comment]
@derwaldgeist How did you fixed that? If I set background to the panel it doesn't makes any difference. And my content isn't moving to the right, I cannot understand what is the problem.
