### ISSUE TITLE
Responsive

### ISSUE THREAD

**Issue by jordanabram1997** [Mango/slideout#134]
Hey There!

I would like to say this plugin looks great however I would like to suggest a few improvements. You could make it that you dont need to press the button for the bar to close and also for it to be responsive like bootstraps navbar 

Thanks

**Comment by montogeek** [comment]
How would you close it?
About the responsive, I think that it's outside of the scope of this package.

**Comment by per-ludum** [comment]
I think it would be quite userfriendly if the menu closes when clicking just *somewhere* on the panel. 

This was my also my own impulse in order to close the menu when testing my site.

**Comment by impronunciable** [comment]
As @montogeek says it's outside the library scope. Somebody else asked the same question and this is the answer https://github.com/Mango/slideout/issues/101

I hope it works for you and if it doesn't please don't hesitate to reopen the issue.
