### ISSUE TITLE
Preventing slideout closing when clicking parent menu items in nav

### ISSUE THREAD

**Issue by ChrisHurrell** [Mango/slideout#136]
How can I prevent the slideout menu closing when I have parent menu items that need to be clicked to reveal sub-menu items?

I've removed the href attribute from parent links but it still closes the slideout nav.

**Comment by ChrisHurrell** [comment]
With the help of StackOverflow I managed to find a hacky solution, which hasn't been tested across browsers yet. I integrated the slideout nav in WordPress, and needed submenu items to work properly. However when clicking on parent menu items to make the submenu items visible, the slideout nav would close. So I used a javascript function to dynamically replace the <a> tags with a random element, in this case <parent>.

But something funny happened, the submenu <a> tags wouldn't click through to their respective URL's. 

I had to loop through each submenu <a> tag and replace the href attribute with onClick window.location attributes. Code below for WordPress users (where you don't have so much control over your nav menu output):

```
jQuery('li.menu-item-has-children > a').each(function() {

  // Create a new element and assign it attributes from the current element
  var NewElement = jQuery("<parent />");
  jQuery.each(this.attributes, function(i, attrib){
    jQuery(NewElement).attr(attrib.name, attrib.value);
  });

  // Replace the current element with the new one and carry over the contents
  jQuery(this).replaceWith(function () {
    return jQuery(NewElement).append(jQuery(this).contents());
  });

});
jQuery('li.menu-item-has-children ul.sub-menu a').each(function() {
  var href = jQuery(this).attr('href');
  jQuery(this).attr('onclick', "window.location='" + href + "'")
         .removeAttr('href');
});
```

Submenu URLs are now working, and the slideout nav doesn't close when clicking parent menu items.

**Comment by pazguille** [comment]
Hi @ChrisHurrell!

You should use the `.preventDefault()` method. When this method is called, the default action of the event, CLICK in this case, will not be triggered.

```js
$('li.menu-item-has-children > a').on('click', function(event) {
  event.preventDefault();
  alert('Hi!');
});
```

Demo: http://codepen.io/anon/pen/YwGEqR

**Comment by ChrisHurrell** [comment]
Thanks pazguille! Quite an obvious solution, not sure why I didn't see that!
