### ISSUE TITLE
2 Menus on the same page.

### ISSUE THREAD

**Issue by DesignPixelZ** [Mango/slideout#139]
I want to use 2 slide-out menus on the same page, one on the left and one on the right. :hamster: 

![buggy](https://cloud.githubusercontent.com/assets/11901639/11400987/186ba310-9399-11e5-8189-4f52a328c028.gif)

**Comment by thesunwave** [comment]
And i want it, but how we can do it?

**Comment by enjoyiacm** [comment]
+1

**Comment by pazguille** [comment]
You could use two instances of Slideout. 
https://github.com/Mango/slideout#how-to-open-slideout-from-right-side

Could you share (http://codepen.io/) the code of your example?

**Comment by xstortionist** [comment]
@pazguille I'm going to add a code pen for the people who are asking about how to achieve this. Working on this now.

**Comment by xstortionist** [comment]
Here is the pen... sorry I know it's a bit messy but shows that this works.

http://codepen.io/xstortionist/pen/GordGp

Here is the javascript:

```javascript
$(document).ready(function() {
    var slideoutLeft = new Slideout({
        'panel': document.getElementById('panel'),
        'menu': document.getElementById('left-menu'),
        'padding': 256,
        'tolerance': 70
    });

    // Toggle button
    document.querySelector('#left-nav').addEventListener('click', function() {
        slideoutLeft.toggle();
    });

    var slideoutRight = new Slideout({
        'panel': document.getElementById('panel'),
        'menu': document.getElementById('right-menu'),
        'padding': 256,
        'tolerance': 70,
        'side': 'right'
    });

    // Toggle button
    document.querySelector('#right-nav').addEventListener('click', function() {
        slideoutRight.toggle();
    });

});
```

Here is the CSS:

```
#left-nav {
	float: left;
}

#right-nav {
	float: right;
}

#right-menu.slideout-menu {
	left: auto;
}

.slideout-menu {
  position: fixed;
  left: 0;
  top: 0;
  bottom: 0;
  right: 0;
  z-index: 0;
  width: 256px;
  overflow-y: auto;
  -webkit-overflow-scrolling: touch;
  display: none;
}

.slideout-panel {
  position:relative;
  z-index: 1;
}

.slideout-open,
.slideout-open body,
.slideout-open .slideout-panel {
  overflow: hidden;
}

.slideout-open .slideout-menu {
  display: block;
}
```

**Comment by pazguille** [comment]
#127

**Comment by xstortionist** [comment]
there is a lingering issue on my example where both menu can show up side by side. I will fix this with CSS, very simple fix.

**Comment by pazguille** [comment]
@xstortionist thank you for share your code! Anyway, I'll work on this feature to avoid create two instances of Slideout.

**Comment by xstortionist** [comment]
@pazguille no problem and sounds good. I still run into issue when I have other elements on page that utilize swipe effects. Is there way to ignore certain elements to not trigger the menu swipe.

**Comment by amir3code** [comment]
See my gist:
https://gist.github.com/amir3code/b6a34c2ee4de6d9053d59a0a65ae06d5
I have done it side by side of vuejs.
