### ISSUE TITLE
Slow load:  unformatted menu showing for a second or two

### ISSUE THREAD

**Issue by chrissun** [Mango/slideout#141]
FYI, i found that my slideout menu was being shown for a second or two during page load (especially on mobile).  Im sure this has to do with load order and the large size of my slideout menu...

The solution was to add the "slideout-menu" class to my "menu" div up front.  Guess with the size and configuration of my page, there was too much of a delay for the addition of the slideout-menu class by the plugin.

**Comment by pazguille** [comment]
> Im sure this has to do with load order and the large size of my slideout menu...

Yeap, The solution is fine but you should organize your code. :)
