### ISSUE TITLE
Publish 0.1.12 release

### ISSUE THREAD

**Issue by jonscottclark** [Mango/slideout#143]
Hey @pazguille, can you publish 0.1.12 as a release so that it gets published to npm? Currently only 0.1.11 is available on npm. Thank you!

**Comment by jonscottclark** [comment]
Bump! :cat:

I think since the package has been built and tagged all you'll need to do is run `npm publish`

**Comment by pazguille** [comment]
Sorry guys! I had some issues. 

Just published v0.1.12.

:D
