### ISSUE TITLE
Is it possible to skip some elements on page?

### ISSUE THREAD

**Issue by ghost** [Mango/slideout#144]
So if we have slideshow with swipe functions, think it's better if slide out skip that element. Is this possible?

**Comment by xstortionist** [comment]
Very good question. So basically you want to ignore slideout dragging when using lets say a touch slider?

Probably best to add some type of data attribute to the element you want ignored so there is no conflict. Not sure best way to go about doing this tho but I'll investigate to the best of my ability.

**Comment by TwanVermeulen** [comment]
+1

**Comment by kpachbiu88** [comment]
What think slideout.js developer about this feature? Will be?

**Comment by larsfjerm** [comment]
Or what about specifying an area/element where the slideout functions works? Now it is the whole panel.

**Comment by pazguille** [comment]
I like the idea to ignore elements using a `data-*`. I will work on this feature soon. :)

**Comment by slzr** [comment]
:+1:  same problem here, i use [owl carousel](http://www.owlcarousel.owlgraphic.com/) and i really want to ignore that element
