### ISSUE TITLE
inner page links don't work on chrome (mobile & windows)

### ISSUE THREAD

**Issue by hardlynoticable** [Mango/slideout#145]
I'm having trouble getting inner page links in the navbar to work in Chrome
(eg. 
		`<li><a href="/#foo">Foo</a></li>`
)
Works fine in Firefox.  I'm using jQuery/bootstrap.  No error; just nothing happens.

**Comment by impronunciable** [comment]
Do you have a link?

**Comment by xstortionist** [comment]
Please provide a preview. Impossible for anyone to troubleshoot without it.

**Comment by hardlynoticable** [comment]
Sorry - The page was in a logged in area - not easy to share - and now I've removed the menu; I'm going to try something else.  

I assume that inner page links USUALLY work?  

Thank you for your time; I'll close this issue.

**Comment by xstortionist** [comment]
codepen.com - paste your code there and you can give us preview. I do not believe it will work with anchor links, which I believe is what you are referencing. I say this because Y scroll is disabled when the menu is revealed.

**Comment by hardlynoticable** [comment]
ic.  You may want to mention that.  I did mean anchor links when I said
inner page links.

As I said;they were working in FF.

I think the line of code that I pasted is probably sufficient; if anchor
links are not expected to work.  Good job though; it's one of the best
swipe capable menus I've seen.  Just not quite what I need.

**Comment by xstortionist** [comment]
@hardlynoticable I have nothing to do with this plugin. I recently started using it and I love how simple and lightweight it is compared to some of the other plugins out there.

Let me test this on my mobile framework and I'll report back with my findings for you.

**Comment by xstortionist** [comment]
I just tested and it works just fine in the newest versions of chrome, firefox and microsoft edge.

This is what I used when testing and I made sure to place the anchor at the bottom of the page.

```
<li><a href="#test"><i class="fa fa-home"></i>Testing 123</a></li>

<a name="test">Testing</a>

```
