### ISSUE TITLE
Fixed Header Issues

### ISSUE THREAD

**Issue by xstortionist** [Mango/slideout#146]
http://codepen.io/xstortionist/pen/GordGp

Noticed when testing that swipe doesn't work on fixed headers, you must swipe outside of the header in order for it to work properly.

Also noticed when swiping there is latency within the animation of the fixed header until the class is added to the header.

Thought I'd pass this along and hope it helps.

**Comment by xstortionist** [comment]
Looks like the only way to fix this issue is to use jquery to animate rather then css. Using jquery to animate will not be as smooth transition but doesn't seem like browsers have caught up with the translate of certain elements.

**Comment by Sandstedt** [comment]
@xstortionist do you have an example of animating with jQuery? Couse I have the same problem as you with the lag of the fixed header.

**Comment by xstortionist** [comment]
@Sandstedt Hi there, I do not have example of animating with jquery as I simply created my own off canvas slideout menu.

**Comment by vitobotta** [comment]
Same issue with the latency...  any suggestions?

**Comment by vitobotta** [comment]
Fixed by wrapping header, content and footer within a wrapper and using that wrapper with Slideout.

**Comment by xstortionist** [comment]
Seems to be an issue with mozilla based browsers. I have seen it on other sites as well.

**Comment by nstanard** [comment]
I'm currently trying to implement a fixed 'sticky' header. I have implemented this before and never really had trouble before. Right now I'm trying to implement a sticky header while also using this Slideout resource. I noticed that the class slideout-panel has a property will-change: transform; that causes fixed elements to not position correctly. Is anybody able to take a moment to help determine a work around? I almost want to just remove that from the styles or override it but am not sure what it does exactly.

**Comment by xstortionist** [comment]
@nstanard would be best to upload something to codepen, kinda hard to help without seeing an example.

Basically, will-change gives a hint to the browser so it can optimize the page ahead of time.

**Comment by nstanard** [comment]
@xstortionist I'll create a small demo so it can help highlight the issue. However - in my 'sticky header' styles I just changed that value to auto and all is good.

**Comment by xstortionist** [comment]
@nstanard if you look at the pen I provided, I have a sticky header but I'm using flex design, which is more powerful and flexible than position: fixed.

**Comment by nstanard** [comment]
Good point - I see that now.

**Comment by xstortionist** [comment]
@nstanard if u upload just a quick preview of what you are experience, I can help. I have actually moved away from this plugin and created my own slide menu which I feel is better than sliding the entire page out of view.

**Comment by xstortionist** [comment]
@nstanard Sorry, I actually changed it to the sticky position based on another thread to show how to have left and right menu sliding out. On my new framework, I simply use flexbox. Sorry for the confusion.

You shouldn't have a problem with onscroll change position to fixed. I will have better idea once I can see what you are seeing.

**Comment by nstanard** [comment]
I'll have to put together a demo - but that'll probably happen tonight at the earliest. I'll get back to you with a link though.

**Comment by pazguille** [comment]
I updated the demo and docs to use `slideout` with a fixed header:
- http://codepen.io/pazguille/pen/ZBxdgw
- https://github.com/Mango/slideout#how-to-use-slideout-with-a-fixed-header

**Comment by artem-schander** [comment]
Sorry to disturb the peace in this old topic. But just so you guys (and possibly other web travelers) are aware.. as far as i can tell there is no need for the event listeners. Its solvable purely by css.

The markup needs a small anjustment, the header `position` needs to be `sticky` and the `overflow` for the body (etc) needs to be `clip`.

See the [Codepen fork](https://codepen.io/artem-schander/pen/yLQMdEE)
