### ISSUE TITLE
ES6 module import

### ISSUE THREAD

**Issue by larsfjerm** [Mango/slideout#149]
When I `import slideout from 'slideout';`, I get an error saying "Cannot set property '_startOffsetX' of undefined".

Is it something I'm missing?

**Comment by impronunciable** [comment]
Not happening to me using webpack + babel. What's your configuration?

**Comment by larsfjerm** [comment]
systemjs + babel.
Do you have any code showing your usage?

**Comment by konpa** [comment]
I think you need to create a new instance, so add `new` before `slideout`:

```javascript
import Slideout from "slideout";

...

this.slide = new Slideout( {
    'panel': document.getElementById('panel'),
    'menu': document.getElementById('menu'),
    'padding': 256,
    'tolerance': 70
});
```

**Comment by larsfjerm** [comment]
Thanks, I forgot to import `Slideout` with an uppercase S.
