### ISSUE TITLE
Move from other side?

### ISSUE THREAD

**Issue by muellernm** [Mango/slideout#15]

**Comment by muellernm** [comment]
Is it also possible to move it from right? or both sides right and left?

**Comment by FlashJunior** [comment]
+1

**Comment by pazguille** [comment]
Not yet :( But we love this improvement! :+1:

**Comment by Charca** [comment]
Created #20

**Comment by Joseffb** [comment]
Yea I would like to move it to the right... +1

**Comment by pazguille** [comment]
#65

**Comment by mytharcher** [comment]
Does it support both 2 menus in each side now?

**Comment by montogeek** [comment]
Yes, create a new Slideout intance with the side option set to `right`, and be sure to add `left: auto` to the [right](https://github.com/Mango/slideout#how-to-open-slideout-from-right-side) menu

**Comment by mytharcher** [comment]
Thanks @montogeek . But it is buggy when I used in both side. The swipe touch event can't be handled properly.

**Comment by montogeek** [comment]
@mytharcher Sorry, I forgot to say that I tested only using a toggle button.

**Comment by mytharcher** [comment]
Yes. I just made it fall back to toggle buttons.
