### ISSUE TITLE
Windows 10 [Mobile] Edge Screen flickering issue 

### ISSUE THREAD

**Issue by backlashsid** [Mango/slideout#152]
On the latest production build of Windows 10 Mobile, upon sliding out the panel the screen flickers upon closing and opening, it seems as if it registers another touch event elsewhere on the screen and sliding out the panel and closing it back is not as smooth as on other browsers. Tested it on iOS9 and it seems to work fine. Could this be related specifically to MS Edge ?

**Comment by pazguille** [comment]
Maybe. I haven't got a window device to test :(

**Comment by denistrustepain** [comment]
iPhone 4s iOS 6 same problem...

**Comment by kokorambo** [comment]
I have same problem not only with Edge browser but also with UC browser. Did you fix this? Thanks!
