### ISSUE TITLE
Enable Touch Events for Panel Close Only

### ISSUE THREAD

**Issue by kerns** [Mango/slideout#154]
I would like to see an option for enabling touch events to close a panel, without enabling touch events for opening a panel.

Because I find myself inadvertently opening or getting a peek of the panel as I scroll/swipe carelessly down the page, making it necessary to set `touch:false` – yet once I open the panel with a button press, being able to swipe it closed is a more natural and easily controlled gesture that is then frustratingly absent.

So something like `touch:close` would be super.

**Comment by kerns** [comment]
Just want to add to this that the issue is perhaps worse under iOS where a swipe from the left edge of the screen is also the history.back gesture of Safari – so trying to open the menu with the gesture triggers this (for me) accidentally some significant % of the time...as does just normal (careless) scrolling.

But closing the open menu with a swipe from right to left doesn't interfere with any gesture, and would be great. All of this assumes a menu on the left side of course.

**Comment by pazguille** [comment]
Hi @kerns !

You can do that using the current API. You should use the `open` and `close` events.

```js
// Create a new instance with touch disabled
var slideout = new Slideout({
  'panel': document.getElementById('main'),
  'menu': document.getElementById('menu'),
  'touch': false
});

// Then, use the slideout `open` and `close` events
slideout.on('open', slideout.enableTouch);
slideout.on('close', slideout.disableTouch);
```

Demo: http://codepen.io/anon/pen/WvavzZ

**Comment by kerns** [comment]
Brilliant. Thank you.

**Comment by pazguille** [comment]
You should execute the function `slideout._initTouchEvents()` just once.
```js
    // Disable touch until opened.
    slideout.once('open', slideout._initTouchEvents); // Here!
    slideout.on('open', slideout.enableTouch);
    slideout.on('close', slideout.disableTouch);
 </script>
```

**Comment by kerns** [comment]
Will do. Thanks again.
