### ISSUE TITLE
Support for Custom (or Improved) Transition Animations

### ISSUE THREAD

**Issue by kerns** [Mango/slideout#155]
Would be nice to see support for more than just the default CSS3 transitions.

Some way to support transitions built via custom cubic bezier values would be great. http://cubic-bezier.com/

The [easeOutBack transition](http://jakiestfu.github.io/Snap.js/demo/apps/settings.html) used by snap.js is very nice – Would like to see slideout expand possibilities here just a bit!

**Comment by pazguille** [comment]
Hi @kerns, slideout now supports cubic-bezier! Demo here: http://codepen.io/pazguille/pen/JbpNQV
