### ISSUE TITLE
How to add a "close" button inside the nav menu

### ISSUE THREAD

**Issue by custardsieve** [Mango/slideout#159]
Hi,
apart from the swipe open and swipe close I would like to add a simple close button inside the menu to close it when user aren't accustomed to swiping close.

Thank you,
David

**Comment by jonscottclark** [comment]
Add an element to the markup in the slideout pane or elsewhere, and bind an event listener on `click` that calls the slideout's `close()` method.

https://github.com/Mango/slideout#slideoutclose
