### ISSUE TITLE
if You click outside of nav , it collapses

### ISSUE THREAD

**Issue by walidmahade** [Mango/slideout#160]
What  would be the necessary code-" if You click outside of nav , it collapses " ? !

**Comment by slzr** [comment]
just add
```javascript
$('#panel').click(function(){
    if ( slideout.isOpen() ){
      slideout.close();
    }    
  });
```
or
```javascript
var panel = document.getElementById('panel');
panel.addEventListener('click', function() {
    if ( slideout.isOpen() ){
      slideout.close();
    }    
});
```
thats works for me

**Comment by slzr** [comment]
I did it my way, but it would be great if this feature was implemented as an option. I found this issue #101 where they explain better what I was trying to achieve.
