### ISSUE TITLE
Jumps to top when menu opens

### ISSUE THREAD

**Issue by nstanard** [Mango/slideout#162]
I followed the basic usage steps and I get this weird issue with the panel scroll position jumps to the top when the menu opens. I feel like it's something I'm doing to cause this but I can't figure out why it's jumping to the top of the content when you open the menu at a scroll position that is not at the top. 

http://codepen.io/nstanard/pen/VaMbom

**Comment by nstanard** [comment]
Is happening when the slideout-open class gets added... removed overflow: hidden; and it's not jumping to the top anymore...

.slideout-open,
.slideout-open body,
.slideout-open .slideout-panel {
/*   overflow: hidden; */
}

**Comment by nstanard** [comment]
Height: 100%; on the html tag causes this.

**Comment by bbatliner** [comment]
I'm having the same issue and identified that style as one reason why. But removing this style results in weird touch behavior, like not being able to close the menu, or the panel/menu getting stuck halfway in between open/closed. I'd love to know why the panel is jumping to the top!

**Comment by matthiasott** [comment]
I had the exact same issue and solved it by removing only the ".slideout-open **body**" from the CSS mentioned above. Don't know if this still leads to weird behavior for you @bbatliner. In my case, the trigger button is placed outside of the .slideout-panel and I can open and close the menu without any problems.

**Comment by bbatliner** [comment]
I was able to fix the issue by leaving all of the styles, but changing other parts of my page so you could still scroll inside the child div, even if the <html> has overflow: hidden.

**Comment by nstanard** [comment]
So, I decided to ditch slideout. Turns out CSS transitions were all I needed for a mobile menu. My solution now simply adds and removes my sso-mobile-nav-is-open class which causesthe CSS to slide the main content over to reveal a mobile menu. Super simple solution. I also use CSS to transition the visibility of the menu while its' open/closed.

`
    /**
     * 
     */
    /* MAIN CONTENT CONTAINER (MOBILE NAV IS CLOSED) */
    #sso-main-content {
        background: $white; 
        transition: transform .3s linear 0s; // header specific
        border-left: 1px solid #f1f1f1; // header specific
        margin-left: -1px; // header specific
        //margin-top: 60*$px; // header specific
        width: calc(100% + 1px); // header specific...
    }

    /**
     * 
     */
    /* MAIN CONTENT CONTAINER (MOBILE NAV IS OPEN) */
    #sso-main-content.sso-mobile-nav-is-open {
        transform: translateX(260px); // 260PX IS THE MOBILE NAV SIZE
        transition: transform .5s linear 0s;
    }
`
