### ISSUE TITLE
Fixed menu with slideout.js (after issue #44)

### ISSUE THREAD

**Issue by koddr** [Mango/slideout#163]
Question to @pazguille after [this answer](https://github.com/Mango/slideout/issues/44#issuecomment-128898518) in issue #44.

How to make non-scroll-to-top content (like as demo: http://codepen.io/anon/pen/NqJGBp) after click humburger for close slideout menu?!

May you show full code of this demo for most understanding?

P.S. I see this trouble only in WebKit browsers (Opera, Chrome, Safari).

**Comment by ahmetsemsettinozdemirden** [comment]
i tried something
```

slideout.on('translate', function(translated) {
    console.log('Translate: ' + translated); // 120 in px
    $('#simenty').css('transition','-webkit-transform 0ms ease');
    $('#simenty').css('-webkit-transform','translateX('+translated+'px)');
    $('#simenty').css('transform','translateX('+translated+'px)');
});

slideout.on('beforeclose', function() {
    $('#simenty').css('transition','-webkit-transform 300ms ease');
    $('#simenty').css('-webkit-transform','translateX(0px)');
    $('#simenty').css('transform','translateX(0px)');
    console.log('End');
});

slideout.on('beforeopen', function() {
    
    $('#simenty').css('transition','-webkit-transform 300ms ease');
    $('#simenty').css('-webkit-transform','translateX(255px)');
    $('#simenty').css('transform','translateX(255px)');
  console.log('End2');
});
```

**Comment by pazguille** [comment]
Hi @koddr. Removing the html { height: 100%; } works fine. Please let me know.

**Comment by pazguille** [comment]
I updated the demo and docs to use `slideout` with a fixed header:
- http://codepen.io/pazguille/pen/ZBxdgw
- https://github.com/Mango/slideout#how-to-use-slideout-with-a-fixed-header
