### ISSUE TITLE
When the menu is open, scroll bar doesn't accommodate the full height of the page

### ISSUE THREAD

**Issue by iruslani** [Mango/slideout#164]
Not sure if anyone has ran into this but I just implemented this plugin on my site and it works great but my menu is only 133px in height and the page is over 1800px. 

When the menu is open, the scroll bar seems to disappear. Closing it makes it appear and the user is allowed to scroll to the bottom of the page itself. It seems that when the menu is open the scroll bar accommodates the menu itself. 

Any idea why this is happening?

Thanks
Iwan

**Comment by Mauth** [comment]
I've noticed this exact scenario in a project i'm working on today. Not only does the scrollbar disappear, but i'm unable to scroll through the page via any other means as well until the menu is closed.

**Comment by Manbearpixel** [comment]
@Mauth Why would you want to enable the behavior of scrolling through your website while the nav is open? If a user has opened a side-nav, then their focus should be on the side-nav and not interacting with the page.

**Comment by Mauth** [comment]
I'm not suggesting that you would want it - simply noting that the behavior exists.

**Comment by pazguille** [comment]
Hi @iruslani, Please, could you share an url to reproduce the issue?

**Comment by WPtouch** [comment]
I would think this is by design— I'm pretty sure it applies overflow:hidden to the content container, to reduce memory consumption on the transform.
