### ISSUE TITLE
0.1.12 breaks youtube fullscreen player

### ISSUE THREAD

**Issue by nhapke** [Mango/slideout#165]
Using the latest version of slideout.js (0.1.12 it is. 0.1.11 is working) together with an iframe embedded youtube player on full screen the actual playing video isn't being shown. All other player items are visible though.

I already investigated and it seems that the style of the `div` showing the video (inside the youtube player iframe) is being set to something like `top: -1600px` at the time the video is starting and therefore is being rendered outside of the view.

I tried to investigate further and I can only assume it has something to do with the decouple library (https://github.com/pazguille/decouple) slideout is based on, as it was updated with the recent version.

Would be great if you can help me resolving this issue. Let me know if you need any additional information.

**Comment by pazguille** [comment]
Hi @nhapke,
Could you share a link? I would like to test it to see what is happening.
Thanks!

**Comment by nhapke** [comment]
Hi @pazguille I am sorry for the late reply here. It wasn't the problem of slideout, but rails-assets (see a similar issue we had here: https://github.com/rails-assets/rails-assets/issues/326). Using the latest version of rails-assets fixed it. Will therefore close this issue.
