### ISSUE TITLE
Implementing  this slideout to an existing website..

### ISSUE THREAD

**Issue by walidmahade** [Mango/slideout#167]
_
**Does any one have a simpler version????!!!!**_
So how do I use this slideout nav with a existing website ?
I mean where does the website  body goes?

I am overwhelmed with the number of different stuffs.

**Comment by Manbearpixel** [comment]
Documentation seemed a little confusing to me as well as to which is the panel and which is the menu. Figured it out though; The `panel` is your website content, whereas the `menu` is the mobile nav menu that will appear when you toggle your `slideout`.

As for adding this to an existing website you'll probably have to adjust the layout or structure of your content. It should just be simple enough to wrap your entire site within an additional block element, such as a `div` or `main` as shown in the example, and add links for mobile users within another block element `div` or `nav` with appropriate IDs.

Here is how I have my site setup:

```erb
<main id="panel">
  <header class="header navbar">
    <%= render 'layouts/header' %>
  </header>

  <div id="content" class="content">
    ...
  </div>
</main>

<nav id="menu" class="" role="navigation">
  <%= render 'layouts/nav_list' %>
</nav>
```

**Comment by walidmahade** [comment]
Thanks, I will try to make this work....
