### ISSUE TITLE
Can I disable Slideout on Google Maps?

### ISSUE THREAD

**Issue by Orsey** [Mango/slideout#168]
Hellow. Tell me please, can I disable Slideout when I drag google map?

I do not wont open menu panel when I drag google map, but I get menu.

Thanks.

**Comment by impronunciable** [comment]
I think this will make it work https://github.com/Mango/slideout/pull/157

**Comment by Orsey** [comment]
Thanks, but how I can use this, after insert all chages in my file?

**Comment by Orsey** [comment]
Thanks, this so as I wanted.
