### ISSUE TITLE
demo why can't touch, Only through click to open navigation

### ISSUE THREAD

**Issue by brotherYoung** [Mango/slideout#169]
copy full example into my project and browse, can't touch or drag, only open navigation with click
Like this？
 document.querySelector('#panel').addEventListener('touch', function() {
        slideout.toggle();
    });

**Comment by pazguille** [comment]
Hi @brotherYoung, Please, could you share an url to reproduce the issue?

**Comment by brotherYoung** [comment]
Hi @pazguille, thanks for answering, this question hava solved,your code is perfect.I did not quite understand, thanks again.
