### ISSUE TITLE
"How to enable slideout only on mobile devices." Bug

### ISSUE THREAD

**Issue by masterwok** [Mango/slideout#171]
There is a bug in the provided example for how to only enable slideout on mobile devices here: [http://codepen.io/anon/pen/xGEdvQ?editors=100](http://codepen.io/anon/pen/xGEdvQ?editors=100)

To reproduce this bug:

1. Shrink the browser's width to the point where the toggle button becomes available.
2. Click the toggle button to bring out the menu.
3. Expand the browser's width until excess margin appears

**Comment by masterwok** [comment]
Here's a dirty hack around: [http://codepen.io/anon/pen/qZwVVQ?editors=0010](http://codepen.io/anon/pen/qZwVVQ?editors=0010)

Javascript:
```

  window.onresize = function() {
    var width = window.innerWidth;
    if (width > 780 && slideout.isOpen()) {
      slideout._opened = false;
      slideout.panel.style.transform = 'translateX(0)';
    }
  };
```

**Comment by pazguille** [comment]
Thanks! The updated example here: http://codepen.io/pazguille/pen/mEdQvX
