### ISSUE TITLE
Issue when the touched element has horizontal scroll

### ISSUE THREAD

**Issue by levani** [Mango/slideout#172]
I have an element on my mobile website that has a horizontal scroll using `overflow-x: scroll`. The problem is when I start scroll on this element from left to right the menu is opening as well an both slide animations are happening at the same time. Because of this none of it feels smooth.

Here is a small example:
![ezgif com-video-to-gif](https://cloud.githubusercontent.com/assets/184472/15316850/e1f3a074-1c2f-11e6-82c9-21cb7b47d294.gif)
(last two animation is done from outside that element)

I think one solution to this problem would be the ability to prevent the menu from opening if the touched element has class x. This selector can be passed as a config parameter as well.

**Comment by pazguille** [comment]
#144
