### ISSUE TITLE
slideout.min.js:1 Uncaught TypeError: Cannot read property 'search' of undefined

### ISSUE THREAD

**Issue by nishantpant** [Mango/slideout#173]
I keep getting this error. Here is my code. 
slideout.min.js:1 Uncaught TypeError: Cannot read property 'search' of undefined

    <nav id="menu" class="menu slideout-menu">
        <a href="https://github.com/mango/slideout" target="_blank">
            <header class="menu-header">
                <span class="menu-header-title">Client Connect</span>
            </header>
        </a>

        <section class="menu-section">
            <h3 class="menu-section-title">Menu</h3>
            <ul class="menu-section-list">
                <li><a href="https://github.com/mango/slideout" target="_blank">Register</a></li>
                <li><a href="https://github.com/mango/slideout/issues/new" target="_blank">Sign-In</a></li>
            </ul>
        </section>
    </nav>

<main id="panel">
    <header>
        <button class="toggle-button">☰</button>
    </header>
</main>

    <script type="text/javascript">
        $(document).ready(function () {
            var slideout = new Slideout({
                'panel': $('#panel'),
                'menu': $('#menu'),
                'padding': 256,
                'tolerance': 70
              });

            // Toggle button
            $('.toggle-button').on('click', function () {
                slideout.toggle();
            });
        });
    </script>

**Comment by impronunciable** [comment]
The issue is you are passing jQuery objects instead of DOM elements. Try with this instead:

```
<script type="text/javascript">
    $(document).ready(function () {
        var slideout = new Slideout({
            'panel': $('#panel').get(0),
            'menu': $('#menu').get(0),
            'padding': 256,
            'tolerance': 70
          });

        // Toggle button
        $('.toggle-button').on('click', function () {
            slideout.toggle();
        });
    });
</script>
```
