### ISSUE TITLE
Visual bug when closing

### ISSUE THREAD

**Issue by bot4343** [Mango/slideout#177]
I have this visual bug when try close menu
![animation](https://cloud.githubusercontent.com/assets/14108575/16585073/ba02dca6-42c7-11e6-898e-5d21ba8e9bc9.gif)
This code will fix that:
```
#main {
  background: white;
  height: 100vmin!important;
}
```
But it dosn't work in mobile browsers.

**Comment by pazguille** [comment]
Hi @bot4343 , Please, could you share an url to reproduce the issue?

**Comment by bot4343** [comment]
@pazguille https://codepen.io/bot4343/pen/KrvmRp

**Comment by lunswor** [comment]
@bot4343 this happens for me when the slideout-panel height is not 100%. Try adding `height:100%;` to `.slideout-open, .slideout-open body, .slideout-open .slideout-panel`

I'm not sure what effect this will have on anything else.
