### ISSUE TITLE
 drawer expanded on large display

### ISSUE THREAD

**Issue by fortm** [Mango/slideout#178]
Currently , the drawer is collapsed by default even on large displays. 
Is there a way to have it always expanded on large display and converting to expandable drawer on smaller devices ? On large display, there would be drawer and main content always visible in this case converting to menu icon in smaller display.

**Comment by impronunciable** [comment]
As @pazguille showed on another issue (#77) you can use media queries. This is an example http://codepen.io/anon/pen/xGEdvQ?editors=100
