### ISSUE TITLE
When you open the menu does not maintain the scroll position

### ISSUE THREAD

**Issue by williamcosta** [Mango/slideout#180]
I have a problem in the mobile version of my website, that when opening the scroll menu is not respected and the site back to the top.

Has anyone had this problem?

**Comment by kemalkolayca** [comment]
Yes I have recently experienced the same problem and even though it is not a big thing, I would prefer that the scroll position not to be changed.

**Comment by kemalkolayca** [comment]
I tried something like this:

```
/*
.slideout-open,
.slideout-open .slideout-panel,
*/
.slideout-open body {
 overflow: hidden;
}
```
Just try to apply _overflow: hidden_ to body tag.

**Comment by williamcosta** [comment]
Yes, I'm using this way but the error continues.

**Comment by call007** [comment]
Deleted:
html {
    height: 100%;
}

**Comment by lesliechw** [comment]
@call007,

May I know which and where html CSS exist? Please advice, thank you.

Regards

**Comment by queiroz** [comment]
Removing the html `{ height: 100%; }` works, whoever it does not solve the problem for those who need it with sticky footer.

**Comment by pazguille** [comment]
You could use `beforeopen` and `beforeclose` events to update the height of your layout to 100% only when needed.
