### ISSUE TITLE
Slideout on trigger jquery fadeIn/out not working

### ISSUE THREAD

**Issue by sooxiaotong** [Mango/slideout#182]
slideout.on('open', function() {
alert("opened");
 $(".navbar").FadeIn('fast');
});

**Comment by pazguille** [comment]
Hi @sooxiaotong! The jQuery function is called `.fadeIn` in lowercase. Is the alert() working?

**Comment by sooxiaotong** [comment]
The alert works find. By the way I found the solution by using "document.querySelector"
