### ISSUE TITLE
Swipe from left gesture on desktop

### ISSUE THREAD

**Issue by rctneil** [Mango/slideout#183]
I wish to only use slideout on my mobile site. I have it working but the left swipe gesture still activates the menu on desktop. How can this be disabled? I've looked at the CodePen examples on mobile vs desktop and it's on there but cannot seem to find how that's implemented?

**Comment by pazguille** [comment]
Hi @rctneil, You could use this solution: https://github.com/Mango/slideout#how-to-enable-slideout-only-on-mobile-devices
