### ISSUE TITLE
Uncaught TypeError: Cannot read property 'className' of null

### ISSUE THREAD

**Issue by clamarque** [Mango/slideout#185]
Hello !

try to implemente in my app and i get this error on Chrome v-48 and slideout.js v-0.1.12: Uncaught TypeError: Cannot read property 'className' of null.

I followed what was written in the installation , but here is my code :

`<div id="menu" class="col-xs-12 col-sm-2 col-md-2 sidebar card">
</div>`

`<div id="panel" class="col-xs-12 col-sm-10 col-md-10">
        <header>
            <button class="toggle-button">☰</button>
            <h2>Panel</h2>
        </header>
        <router-outlet></router-outlet>
    </div>`

and my JS: 

`  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script> 
  <script src="https://cdnjs.cloudflare.com/ajax/libs/slideout/0.1.12/slideout.min.js"></script>
    <script>
        var slideout = new Slideout({
            'panel': document.getElementById('panel'),
            'menu': document.getElementById('menu'),
            'padding': 256,
            'tolerance': 70
        });
    </script>`

Thank !

**Comment by Laniman** [comment]
@clamarque, your code works - http://codepen.io/laniman/pen/qNQxPN

**Comment by clamarque** [comment]
Indeed. I use angular2 . I think it does not load the files if they are not stated in the systemconfig file. Thank you !
