### ISSUE TITLE
Move focus from button to first item in menu

### ISSUE THREAD

**Issue by mrbrimm** [Mango/slideout#186]
I can;t seem to find where/how the focus is being set back on the button and I need to set it on the first item in the menu for accessibility reasons. Can you point me in the right direction?

**Comment by pazguille** [comment]
Hi @mrbrimm , you can use the `translateend` event to set focus on the first item:
```js
slideout.on('translateend', function () {
  if (slideout.isOpen()) {
    document.querySelector('#example-first-item').focus();
  }
});
```
