### ISSUE TITLE
Slideout menu won't work if html contains words 'slideout-menu'

### ISSUE THREAD

**Issue by codefuhrer** [Mango/slideout#187]
This doesn't work:

``` html
<!-- I'm binding my js to bem-like markup with js- prefix, not IDs: -->
<nav class="js-slideout-menu">
    ...
</nav>
```

Because [this](https://github.com/Mango/slideout/blob/master/index.js#L70) will return true. 

Script's logic should be similar to [`element.classList.contains()`](https://developer.mozilla.org/en-US/docs/Web/API/Element/classList#Methods) method.

**Comment by pazguille** [comment]
#196
