### ISSUE TITLE
I want to create click => "overlay" => click on overlay close the menu

### ISSUE THREAD

**Issue by Siton-Systems** [Mango/slideout#188]
Like in Waze, and most the of the Apps (Or like this - click on the dark area):
http://materializecss.com/side-nav.html

Better ui pattern!!

Someone have codepen or guide? (Even for a pay i want to fix this. Send me massage her or in skype "siton-her").

**Comment by lesliechw** [comment]
You can add "touchstart" event listener to your "panel" element, then add slideout.close(); to the event function. I do the same to my own app.

Hope it help.

**Comment by Siton-Systems** [comment]
Why this is not "build in" ? :(

How you create the "big" overlay button?

**Comment by rogerhnn** [comment]
I am trying to implement that too. When the menu is opened the add a dark overlay over panel, and if you click that overlay, the menu closes, or if you slide-it to close remove the overlay.
Any help?

**Comment by pazguille** [comment]
Hi @rogerhnn and @Siton-Systems,

The feature is not "build in" because I would like to keep slideout.js as tiny as possible. But you can do it from outside thanks to the powerful API and a little extra CSS.

You can checkout out this demo: http://codepen.io/pazguille/pen/BQYRYK

**Comment by KingteEGER** [comment]
Is there a drag Event to set the darken stronger and lower depending on how far the menue is open?

**Comment by pazguille** [comment]
Hi @KingteEGER. You can use the `translatestart`, `translate` and `translateend` events (available only with touch events).

**Comment by KingteEGER** [comment]
Hm I don't get it, why my snipped doesn't work: (depending on http://codepen.io/pazguille/pen/BQYRYK)
            slideout.on('translate', function(translated) {      
              this.panel.style.backgroundColor = 'rgba(0, 100, 0, '+ (120/100)*translated +')';               
            });

Happy new Year.

**Comment by pazguille** [comment]
Hi @KingteEGER, you should try this, but in my opinion is not the best approach.

```js
slideout.on('translate', function(translated) {
  this.panel.style.backgroundColor = 'rgba(0, 100, 0, '+ translated/100 +')';
});
```
