### ISSUE TITLE
Define Touch Zone for Slide Open

### ISSUE THREAD

**Issue by lesliechw** [Mango/slideout#189]
Hello to all,

In my app, google map is at full screen. So when I move around the map by touch gesture, the side menu will open as normal. This is not good.

Anyway to make the slide open gesture only at far left or far right? Something like the edge of left or right. So when interacting with the map at the middle/center of the app, the side menu won't slide out.

Please advice, thank you.

**Comment by marysgonzalez** [comment]
+1

**Comment by impronunciable** [comment]
This is a duplication of https://github.com/Mango/slideout/issues/168 which can be fixed with https://github.com/Mango/slideout/pull/157

let me know if that works
