### ISSUE TITLE
Slideout.close() method doesn't remove slideout-open class from html tag

### ISSUE THREAD

**Issue by alexandr-bbm** [Mango/slideout#196]
Thank the authors for this nice lib. 

We noticed some kind of bug case:
User opens a modal popup from slideout menu. Our modal component adds class `modal-open` to the `<body >` tag via jQuery.addClass() method. So, the class attribute of `<body>` tag changes from ' slideout-open`to 'slideout-open modal-open` (please notice a dissapeared space before slideout-open). Then, we need to close slideout programmatically which is done by Slideout.Close() method. However, this method removes the class in the following way:
`html.className = html.className.replace(/ slideout-open/, '');
`[Source: Line 123](https://github.com/Mango/slideout/blob/master/dist/slideout.js)
i.e. it supposes class `slideout-open` to have a space before it. 

Why can't we replace `slideout-open` class without the space before it? This will solve this case and will not break any other.

**Comment by pazguille** [comment]
Hi @alexandr-bbm! Yes, you are right. I'm going to work on a new version using `classList` to avoid these issues with `.add()` and `.remove()` methods.
