### ISSUE TITLE
Sliding out doesn't animate

### ISSUE THREAD

**Issue by TheConsciousness** [Mango/slideout#198]
I'm using the basic example listed on the website. When hitting the toggle button to slide the menu out, the toggle button makes its way to the edge of the screen and then the menu disappears without any closing animation.

Here is my code, though CodePen won't handle this correctly.
http://codepen.io/anon/pen/VKBwkm

**Comment by pazguille** [comment]
Hi @TheConsciousness! You could check out this demo http://codepen.io/anon/pen/NqJGBp when the animation works fine.

Could you fix your CodePen demo to see it in action?

**Comment by TheConsciousness** [comment]
Hi there. I'm using the example snippets from the front page of the GitHub, and can replicate that it will slide open, but once sliding out, the content on the page "blinks out" instead of sliding.

Codepen is broken, but here is a copy.
https://codepen.io/bot4343/pen/KrvmRp

**Comment by pazguille** [comment]
Hi @TheConsciousness, I update your codepen and now works fine. I think the problem is with your layout heights. The height of the main content is more less than the navigation's height, so when you open / close the slideout you see the issue.

Fixed: http://codepen.io/anon/pen/wowMQL
