### ISSUE TITLE
How can I use it in rem design page?

### ISSUE THREAD

**Issue by endingman** [Mango/slideout#201]
I use it like this:
var slideout = new Slideout({
        'panel': document.getElementById('main'),
        'menu': document.getElementById('menu'),
        'padding': 90,
        'tolerance': 70,
        'side':'right'
    });
but I want to use 'padding':'4rm' Instead  'padding': 90,it does not work!

**Comment by pazguille** [comment]
Hi @endingman. Slideout only support `px` units.

**Comment by wl05** [comment]
you can get the font size of  html tag, then document.documentElement.style.fontSize.split('px')[0] * 7.5 + 'px'
