### ISSUE TITLE
[question] vertical slide out (from bottom-up)?

### ISSUE THREAD

**Issue by tconroy** [Mango/slideout#204]
Hey there..

Wondering if it's possible to use slideout as a vertical menu, instead of horizontal? ( imagine the settings drawer on iOS, when a user slides their finger upwards from the bottom of the screen, the drawer opens ).

**Comment by pazguille** [comment]
Hi @tconroy, the slideout only works horizontally for now.

**Comment by tconroy** [comment]
Hi @pazguille -- that's unfortunate. :( Thank you for answering my question! By any chance, do you happen to know of any other similar js libs that support vertical slide outs?

Thank you!
