### ISSUE TITLE
Unable to preventDefault inside passive event listener

### ISSUE THREAD

**Issue by evanre** [Mango/slideout#205]
Hi, thank you for a great plugin. I found an issue, but I don't know how much it serious. You also can see this issue on your pluggin [page](https://mango.github.io/slideout/).
When I trying to open navigation by swiping from edge (not by tapping on the button) in mobile device emulation in Chrome devtools, I get the same error many times:
`Unable to preventDefault inside passive event listener due to target being treated as passive. See https://www.chromestatus.com/features/5093566007214080`.

**Comment by pazguille** [comment]
Hi @evanre! On Chrome Version 54.0.2840.98 (64-bit) for OSX works fine and no warning in console.

**Comment by evanre** [comment]
Hello, @pazguille, thanks for a quick response. It strange :) There is screenshot, Windows 10, Chrome 55 64bit. Anyway, all works good.
![2016-11-12_23-02-36](https://cloud.githubusercontent.com/assets/12615906/20240863/343b3ba6-a92c-11e6-8c2b-3de6e1676989.png)

p.s. I have a small question. How I can change option value after creating instance? 
I've set different width for navigation on different screen resolutions. And I want check on every opening the width and if it was changed (e. g. orientation was changed from portrait to landscape), to change the "padding" value.

**Comment by pazguille** [comment]
Hey @evanre, You can change the padding updating the value of the property `_padding` and  also you should update the value of `.slideout-menu` width.

```js
slideout._padding = 500;
```

```css
.slideout-menu {
  width: 500px;
}
```

**Comment by widoz** [comment]
As per documentation, if the event is passive you can't call preventDefault, for more info read https://goo.gl/c5XRhE.

> passive: A Boolean indicating that the listener will never call preventDefault(). If it does, the user agent should ignore it and generate a console warning.

Hope this help.

**Comment by RByers** [comment]
As for the warning from Chrome: sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention).  There's probably a missing `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), which is necessary to support touch on IE/Edge anyway.  Your fix may cause problems on browsers which don't support passing options to `addEventListener` because you didn't use [feature detection](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection).

**Comment by honeyamin** [comment]
> As for the warning from Chrome: sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention). There's probably a missing `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), which is necessary to support touch on IE/Edge anyway. Your fix may cause problems on browsers which don't support passing options to `addEventListener` because you didn't use [feature detection](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection).

So any solution?

**Comment by honeyamin** [comment]
> > As for the warning from Chrome: sorry for the trouble, this is a breaking change in Chrome 56 to [improve scroll performance](https://developers.google.com/web/updates/2017/01/scrolling-intervention). There's probably a missing `touch-action` [CSS rule](https://developer.mozilla.org/en-US/docs/Web/CSS/touch-action), which is necessary to support touch on IE/Edge anyway. Your fix may cause problems on browsers which don't support passing options to `addEventListener` because you didn't use [feature detection](https://github.com/WICG/EventListenerOptions/blob/gh-pages/explainer.md#feature-detection).
> 
> So any solution?

i use css trick and resolve that but i think it need feauture detection in future;**BUT** now it resolved
add to **panel** style
`touch-action: manipulation;`

**Comment by everythinginjs** [comment]
@honeyamin  nice trick dude,
