### ISSUE TITLE
How to disable slideout on iPad and enable only for mobile?

### ISSUE THREAD

**Issue by lmi11** [Mango/slideout#206]
How to disable slideout on iPad and enable only for mobile?

**Comment by pazguille** [comment]
Hi @lmi11, You should check it out [how-to-enable-slideout-only-on-mobile-devices](https://github.com/Mango/slideout#how-to-enable-slideout-only-on-mobile-devices) docs section.

Algo, you could use a library to detect iPad or tablet devices and then disable slideout:

```js
if (device === 'tablet') {
  slideout.disableTouch();
} else if (device === 'mobile') {
  slideout.enableTouch();
}
```
