### ISSUE TITLE
100% width not 100%.

### ISSUE THREAD

**Issue by TimMeade** [Mango/slideout#213]
We are trying to have a 100% width slide.   The menu should completely push the visible page off.  We will then close the slide out with a button on the menus restoring the site.   No matter what we try this does not seem to work.  There is always a bit of the site still visible on the edge.

Is this possible?   

Thanks

Tim

**Comment by pazguille** [comment]
Hi @TimMeade, I built a simple demo, please check it out and let me know if works fine for you. 
http://codepen.io/pazguille/pen/KNxeMx

**Comment by TimMeade** [comment]
Thanks.

This worked

**Comment by TimMeade** [comment]
Found an issue with this.   If vertical on phone and then rotated without reloading it no longer goes 100% width.

Thanks

Tim
