### ISSUE TITLE
Menu width when close

### ISSUE THREAD

**Issue by balkarov** [Mango/slideout#214]
Hello!
Thank you for your library!
How I can change menu width when it is close? It is possible?
For example
![home11](https://cloud.githubusercontent.com/assets/6030335/21241106/3cab663c-c31f-11e6-885e-e4a48fa3cad9.jpg)

**Comment by pazguille** [comment]
Hi @balkarov, Sorry but you can not change the width of the  menu on close. I'll working on add this feature on future versions.

**Comment by balkarov** [comment]
Thank you so much! You are cool! 
I will be waiting. Can you inform, when you release this version, please

**Comment by forpenguinonly** [comment]
Hi @pazguille, is this feature available yet? Thanks! :-)
