### ISSUE TITLE
Change width of panel on different devices

### ISSUE THREAD

**Issue by hiphoptime** [Mango/slideout#219]
Hello!
I want change menu width on other devices. For example on < 992px - 260px | > 992px - 600px.
I did it when the page loads, but does not work when resizing...

![Screenshot](http://i63.tinypic.com/oiua6u.jpg)

It is possible to change the size of the panel on different devices?
Can you help me?
Thank you.

```
.slideout-menu
  position: fixed
  width: 600px
  .l-sidebar-nav-menu
    li
      &.l-sidebar-nav-footer
        a
          &:first-child
            display: none

@media only screen and (max-width: 991px)
  .slideout-menu
    width: 260px
  .l-sidebar-nav-menu
    li
      &.l-sidebar-nav-footer
        a
          &:first-child
            display: block
```

    $(window).resize(function(){
        isMobile = $('.l-sidebar-nav-footer a:first-child').is(':visible')
    }).resize();

    if (isMobile == true){
        var SlideoutChangeWidth = 260;
    } else {
        var SlideoutChangeWidth = 600;
    }

	var slidePanel = new Slideout({
		'panel': document.getElementById('content-slide'),
		'menu': document.getElementById('panel-slide'),
		'padding': SlideoutChangeWidth,
		'tolerance': 70,
        'easing': 'cubic-bezier(.32,2,.55,.27)'
	});

	var fixedHeader = document.querySelector('.l-sticky-header, .l-header');
	var mainHeader = document.querySelector('.l-header');

	var allBurgers = $('.slide-panel .hamburger');

	$('.slide-panel').on('click', function() {
		slidePanel.toggle();
	});

	function close(eve) {
		eve.preventDefault();
		slidePanel.close();
	}

	slidePanel
		.on('translate', function(translated) {
			fixedHeader.style.transform = 'translate3d(' + translated + 'px, 0, 0)';
			mainHeader.style.transform = 'translate3d(' + translated + 'px, 0, 0)';
		})
		.on('beforeopen', function() {
			this.panel.classList.add('panel-open');

			fixedHeader.style.transition = 'transform 300ms ease';
			fixedHeader.style.transform = 'translate3d(' + SlideoutChangeWidth + 'px, 0, 0)';
			mainHeader.style.transition = 'transform 300ms ease';
			mainHeader.style.transform = 'translate3d(' + SlideoutChangeWidth + 'px, 0, 0)';

			allBurgers.addClass('is-active');
		})
		.on('open', function() {
			this.panel.addEventListener('click', close);

			fixedHeader.style.transition = '';
			mainHeader.style.transition = '';
		})
		.on('beforeclose', function() {
			this.panel.classList.remove('panel-open');
			this.panel.removeEventListener('click', close);

			fixedHeader.style.transition = 'transform 300ms ease';
			fixedHeader.style.transform = 'translate3d(0, 0, 0)';
			mainHeader.style.transition = 'transform 300ms ease';
			mainHeader.style.transform = 'translate3d(0, 0, 0)';

			allBurgers.removeClass('is-active');
		})
		.on('close', function() {
			fixedHeader.style.transition = '';
			mainHeader.style.transition = '';
		});

**Comment by pazguille** [comment]
Hi @hiphoptime,

The slideout API does not support this case, but you can update some values on resize to do that:
```js

var MOBILE_WIDTH = 260;
var DESKTOP_WIDTH = 600;

var isMobile;
var SlideoutChangeWidth;

$(window).resize(function(){
  isMobile = $('.l-sidebar-nav-footer a:first-child').is(':visible')

  // You should improve this logic to avoid unnecessary updates.
  SlideoutChangeWidth = isMobile ? MOBILE_WIDTH : DESKTOP_WIDTH;
  if (slidePanel) {
    slidePanel._padding = slidePanel._translateTo = SlideoutChangeWidth;
  } 
}).resize();

// Create slideout instance width this value as `padding`
var slidePanel = new Slideout({
  'panel': document.getElementById('content-slide'),
  'menu': document.getElementById('panel-slide'),
  'padding': SlideoutChangeWidth,
  'tolerance': 70,
  'easing': 'cubic-bezier(.32,2,.55,.27)'
});

{ ... }
```

**Comment by hiphoptime** [comment]
I changed the code considering the recommendations, but the momentary transformation on resize hasn't followed...
![Screenshot](http://i65.tinypic.com/104graf.jpg)
I can not imagine how to make it work =(
Сan you give an example of this implementation? (jsfiddle,codepen)

**Comment by devoto13** [comment]
I came up with the following code to make menu always occupy 80% of the screen, but no more than 400px. It seems to work correctly with both closed and open drawer. 

```js
window.onresize = function() {
  let menuSize = Math.min(Math.round(document.body.offsetWidth * 0.8), 400);
  slideout._padding = menuSize;
  slideout._translateTo = slideout._orientation * menuSize;
  if (slideout.isOpen()) {
    slideout._translateXTo(slideout._translateTo);
  }

  document.querySelector('.slideout-menu').style.width = menuSize + 'px';
};
```
