### ISSUE TITLE
use the back button in smart phone to close menu

### ISSUE THREAD

**Issue by the94air** [Mango/slideout#220]
I want to add new feature using the back button in the phone by adding for examples `slideout.html#menu` so the use can  click the back button to close the slide menu

**Comment by Buom01** [comment]
Hi,
Here is my simple exemple using JQuery and Browserify (For who want an exemple):
```javascript
    var Slideout = require("slideout");
    slideout_menu = new Slideout({
      'panel': $('#panel')[0],
      'menu': $('#menu')[0],
      'padding': 256,
      'tolerance': 50
    });
    if ("onhashchange" in window) {
      slideout_menu.on('open', function() {
        window.location.hash = "#menu";
      });
      slideout_menu.on('close', function() {
        window.location.hash = "";
      });
      $(window).bind('hashchange', function() {
        if (window.location.hash == "#menu") {
          slideout_menu.open();
        }else{
          slideout_menu.close();
        }
      });
    }
```

**Comment by the94air** [comment]
Seriously :man_facepalming:  3 month to reply. WOW where have you ever been ?? I hope you are good.
I have never used the `window.location.hash`. It is nice way to do that. Thanks.

**Comment by Buom01** [comment]
It's because there are so many explanation on the web for similar issues, and actually it's seem to be the only and the best solution (cross platform).
I have no links with the package except that I'm a user

**Comment by the94air** [comment]
@Buom01 there was a miss understanding. Sorry, I thought you are the owner of this repository. and I realize that today. Thank you very much for help. I really appreciate that :+1:
