### ISSUE TITLE
Close the menu if browser width is a certain value

### ISSUE THREAD

**Issue by sbungert** [Mango/slideout#222]
Is it possible to close the menu when the browser is resized to a certain width? I'm using it to show naviagtion on mobile devices (via a hamburger meu) but if the window size is changed and enough room is available the hamburger button disappears and the main navigation in the page header is shown again.

In such a case I need the slide in menu to hide itself again.

**Comment by impronunciable** [comment]
@sbungert you can take the decision inside an event listener and then use `slideout.open()` and `slideout.close()`. For example:

```js
document.addEventListener('resize', function() {
  if (window.innerWidth < 800 && slideout.isOpen()) {
    slideout.close()
  }
})
```

Btw try to throttle the resize event handler
