### ISSUE TITLE
Target the element that accepts the touch events

### ISSUE THREAD

**Issue by lmartins** [Mango/slideout#23]
Im having an issue where a slider that has touch events is conflicting with slideout. The problem is that when trying to interact with the slider, both the slider and slideout will do their things and the app breaks.

Is there anything I can do to prevent this?

**Comment by RomanShabanov** [comment]
Could you provide your code?
The easiest solution is to detect the event.target and in case it's a slider don't runt slideout

**Comment by lmartins** [comment]
I see what you mean, it would do the trick, although im not finding the way to do it.

Im initialising slideout like this:
```
var slideout = new Slideout({
            'panel': document.getElementById('main-panel'),
            'menu': document.getElementById('offcanvas-panel'),
            'padding': 256,
            'tolerance': 70
        });
```

And my code is something in the lines of:

```
<div id="main-panel>
   main content
  <div class="slider">slider</div>
</div>

<div id="offcanvas-panel>
    slideout panel
</div>
```

Could you please provide some direction where to look for?

**Comment by emailmike1994** [comment]
I've also run into an issue where slideout and a slider are in conflict.  If you try and interact with the slider on mobile, slideout seems to take precedence and your swipe controls that rather than the slide.  Is there any way to disable that swipe interaction and only have slideout function on a click/touch of the hamburger menu?

**Comment by RomanShabanov** [comment]
I am not using this library so I can't run any tests.

There is clear part:
<pre><code>
this.panel.addEventListener(touch.start, function(eve) {
    self._moved = false;
    self._opening = false;
    self._startOffsetX = eve.touches[0].pageX;
    self._preventOpen = (!self.isOpen() && self.menu.clientWidth !== 0);
  });</code></pre>

go for validating the <code>eve.target</code>.
In case you don't want touch support create a variable <code>var touch = false;</code> and validate it before any touch.event

**Comment by emailmike1994** [comment]
I'm not too savvy with Javascript.  I'm not at all sure how to implement the solution above.  Is there anything baked into the Slideout code to disable swipe interactions?

**Comment by pazguille** [comment]
Now, you can use the `touch` option to disable touch events.

```js
var slideout = new Slideout({
  'panel': document.getElementById('main-panel'),
  'menu': document.getElementById('offcanvas-panel'),
  'padding': 256,
  'tolerance': 70,
  'touch': false
});
```
