### ISSUE TITLE
Fixed header workaround

### ISSUE THREAD

**Issue by qwervo** [Mango/slideout#233]
I have my header with position:fixed for always showing it independently of the scroll position.  When I implement the slideout menu, the header doesn't stick to the top of the page. This is my HTML setup:
```
<nav id="menu">
<!-- Nav content-->
</nav>
<main id="panel">
<header style="position: fixed;top: 0;left: 0;"> <!-- Header content--> </header>
<div class="content"><!-- Page content--></div>
</main>
```

Does anyone know how to solve this issue? I really need my header fixed at the top of the page.
Thans in advance

**Comment by pazguille** [comment]
Hi @qwervo,

You should read the following FAQ: https://github.com/Mango/slideout#how-to-use-slideout-with-a-fixed-header
