### ISSUE TITLE
Disabling the Swipe 

### ISSUE THREAD

**Issue by peachesandguacamole** [Mango/slideout#235]
Is there a way to disable the swipe function to access the menu?, so it's only accessible via the toggle.

Often when scrolling around my site it's very easy accidentally swipe and end up in the nav menu by accident. Which .js file contains the options to turn this off?

**Comment by gundarmode** [comment]
add data-slideout-ignore to <main> tag

<main id="panel" data-slideout-ignore>

**Comment by pazguille** [comment]
Hi @peachesandguacamole,

You should create your Slideout instance with the option `touch` in `false`:

```js
const slideout = new Slideout({
  panel: document.getElementById('main'),
  menu: document.getElementById('menu'),
  padding: 256,
  tolerance: 70,
  touch: false,
});
```
