### ISSUE TITLE
Jekyll variables break slideout script and create errors.

### ISSUE THREAD

**Issue by Delatoni** [Mango/slideout#24]
I'm trying to use Slideout.js on a Jekyll site that I'm building but, when I try to use Jekyll variables for the navigation it creates an error and break the script. Here's the markup I'm using...
 
```html
<nav id="menu">
    <ul>
        <li><a href="{{ site.baseurl }}" title="Home">Home</a></li>
        <li><a href="{{ site.baseurl }}/about/" title="About">About</a></li>
    </ul>
 </nav>
```

Here's the error I get...
```js
Uncaught TypeError: Cannot read property 'className' of null
```

**Comment by pazguille** [comment]
Did you create a new instance of the Slideout?
```js
var slideout = new Slideout({
  'panel': document.getElementById('panel'),
  'menu': document.getElementById('menu'),
  'padding': 256,
  'tolerance': 70
});
```

**Comment by Delatoni** [comment]
Yeah I have everything setup the way it should be and it works once I remove those Jekyll variables but, the second I add them back in I get that error I posted above and it stops working. If you want you can view my repo and confirm for yourself the issue I'm seeing if that helps at all.

Link to scripts file here...
https://github.com/Delatoni/donatoni/blob/gh-pages/_includes/scripts.html

Link to Slideout Jekyll partial here...
https://github.com/Delatoni/donatoni/blob/gh-pages/_includes/slideout-menu.html

Link to Default layout here...
https://github.com/Delatoni/donatoni/blob/gh-pages/_layouts/default.html

**Comment by pazguille** [comment]
You should use the id `main` instead of `panel`:

```js
var slideout = new Slideout({
  'panel': document.getElementById('main'),
  'menu': document.getElementById('menu'),
  'padding': 256,
  'tolerance': 70
});
```

:)

**Comment by Delatoni** [comment]
Wow, I feel like an idiot lol. I swear I triple checked everything but, apparently I'm blind lol. Well everything works and you where right. Thanks for the help pazguille and keep up the good work!
