### ISSUE TITLE
AngularJS Support

### ISSUE THREAD

**Issue by brandon-barker** [Mango/slideout#27]
Hi,

Very nice work, would love to use this in an Ionic project I'm busy with - do you have any plans to support AngularJS?

Thanks

**Comment by danzajdband** [comment]
Hi @brandon-barker. This project use web standars that are fully compatible with AngularJS so you can use it as it is. If you are thinking about creating a directive on top of Slideout.js so it's easier to include in your own project is welcome but will not be a part of this library.
