### ISSUE TITLE
Is this being maintained?

### ISSUE THREAD

**Issue by panoply** [Mango/slideout#281]
Is this project still being maintained?

**Comment by bhartvigsen** [comment]
I'm not sure but I spent more time trying to get it to work than building an equivalent slider from scratch using CSS transitions. I think if you put it into a greenfield project it might be ok but it isn't "self defensive" enough to override whatever my stack of frameworks was doing to it. In the end it only took me 20 mins or so to write one from scratch so I'm not sure the benefit this lib is supposed to confer.

**Comment by panoply** [comment]
@bhartvigsen In a javascript world dominated by the virtual dom building an equivalent nowadays is always going to be a logical choice but Slideout still has its place and you can easily cook it into SPA frameworks, for example on [mithril](http://mithril.js.org) you'd just initialise slideout via `oncreate` passing through the `dom` attribute for its selectors. 

Slideout has well thought through event dispatching, option customisation and flexibility. It solves issues when you're working on action heavy components that need to apply configuration before, on, off and after interaction with an offcanvas / drawer sidebar. 

There is **15** pull requests open, **48** open issues and this project retains 7.5k stars which means is actively being used in production and I would hate to see this project die.

**Comment by panoply** [comment]
Any insight to would be greatly appreciated:

@pazguille 
@juanrossi 
@peregrinogris

**Comment by peregrinogris** [comment]
@panoply It's being used in production in at least a large site where @pazguille works so I doubt it's going to die.

**Comment by raffis** [comment]
There are many useful pr's pending, will those get merged any time soon?

**Comment by sun** [comment]
Some changes seem to have happened in v2 in https://github.com/Mango/slideout/tree/new-features, which also seems to have incorporated some of the PRs, but without responding on the corresponding issues.
