### ISSUE TITLE
Rails 6 leaves 'slideout-open' after page reload from nav link

### ISSUE THREAD

**Issue by j-devs** [Mango/slideout#298]
Rails 6 leaves 'slideout-open' attached to DOM elements after page reload. Create overflow:hidden lack of scrolling.

I fixed using the following during the Slideout constructor:
`  // Unsets remaining classnames after page reload
  if (html.classList.contains('slideout-open')) {
    html.classList.remove('slideout-open');
  }`

**Comment by darccio** [comment]
This is related to Turbolinks. Thanks for the workaround.
