### ISSUE TITLE
Buggy transition when main content's height is lower than the window

### ISSUE THREAD

**Issue by Golmote** [Mango/slideout#30]
Reproduced at least in Firefox and Chrome. The navigation gets cut during the transition if the height of the main content is lower than the height of the window.

![548fe68d8986e9e11bfe5fa08c128c86](https://cloud.githubusercontent.com/assets/565460/6591760/ada47f34-c7c4-11e4-93c6-08b1e41260d9.gif)

**Comment by jkielman** [comment]
To fix this make the height of the html tag 100%. 

html {height:100%}

**Comment by Golmote** [comment]
I just tried it out, but it didn't change anything.

**Comment by royalaid** [comment]
I, too, am seeing this issue. @jkielman's fix does not seem to work for me either.

**Comment by Golmote** [comment]
Hm you're right. In my case, I had to put it on the `.slideout-wrapper` element, but it solved the issue.

**Comment by SantzDesign** [comment]
I'm having the same issue and `height: 100%;` to the `.slideout-panel` doesn't fix it.

Here's a screenshot...

![slideout-bug](https://cloud.githubusercontent.com/assets/4060852/6765460/f1b8b20a-cfbf-11e4-9d91-650c5f413be4.png)

Using Chrome on Windows 8.1

**Comment by SantzDesign** [comment]
(If anyone go an email... I'm no longer having this issue. It was my mistake.)

**Comment by superlukas** [comment]
```css
html,
body {
  height: 100%;
}

.slideout-menu,
.slideout-panel {
  min-height: 100%;
}
```

If that doesn't work then it's probably your markup. `min-height: 100vh;` should work in all cases.
