### ISSUE TITLE
issue testing demo in Opera and mobile Titanium

### ISSUE THREAD

**Issue by vanderleisp** [Mango/slideout#33]
Demo file works well on Chrome 41, Opera 28, Firefox 38 but testing on old Opera 12 it doesn't work.
As I'm testing this to see if could use it on a cross-platform app being developed using the Titanium platform, then I packed the test demo as a webview and the same problem happening with Opera 12 also shows up there too.
It pass, on both Opera and Titanium, all tests except two: should translateX the panel to the given padding, and the should translateX the panel to 0.
It seems it's related to the translate3d so use "left" instead ??

anyway, nice solution you developed.......

**Comment by danzajdband** [comment]
@vanderleisp Opera 12 has not support for translate3d (http://caniuse.com/#search=translate3d). We are going to add support for browsers without translate3d support. The relevant issue is https://github.com/Mango/slideout/issues/8

**Comment by vanderleisp** [comment]
thanks.
And as per error report on Chrome browser that Titanium embedded into their tool, seems that it also doesn't support translate3d, as the two errors falls back to the test.js where it calls translate3d.

**Comment by vanderleisp** [comment]
today I tested the Titanium's browser with the http://thewebrocks.com/demos/3D-css-tester/ link, as it shows up in the caniuse.com link for translate3d, and it run well.
so seems the integration problem for the titanium isn't that the browser doesn't support translate3d but another one.

**Comment by fcjurado** [comment]
Titanium webviews uses the native browser (webkit browser) in <4.4 versions. On later versions, Chromium version is used. Info: http://docs.appcelerator.com/titanium/3.0/#!/api/Titanium.UI.WebView

Then, I've same issue in native browser in a Galaxy Nexus with Android 4.4.4. The menu doesn't display sliding. It's displayed only on button click. In Chrome 40 it's working well. @vanderleisp, can you try the demo on both browsers?

**Comment by vanderleisp** [comment]
the 2 devices that I have here are 4.1.2 and 4.3 so can't test in a Chromium one to see if it works.
Also the problem is that it display only the click button on upper left side, and below it only the main 4 times "doc" line but nothing below the "doc" lines like the 4 links to outside pages; on right side shows all tests done plus the two errors.
If click the button then page slide to the right and left, as expected.

**Comment by pazguille** [comment]
#8
