### ISSUE TITLE
simple full example on main page isn't working

### ISSUE THREAD

**Issue by timpisti** [Mango/slideout#40]
I copied the full example content and the js in a new .html, and it isn't work.
The .js is loaded, everything in place.

**Comment by danzajdband** [comment]
Can you show us your html file? (create a gist)

**Comment by timpisti** [comment]
Easiest way:
http://test.4i.hu/slideout/m.html

**Comment by pazguille** [comment]
@timpisti the example works fine. You should open it on your touch device or emulate touch events on your browser. 

Btw, if you want to open/close the slideout clicking on the button you should add the following code:

```js
document.querySelector('#panel button').addEventListener('click', function() {
  slideout.toggle();
});
```
I'm going to update the full example adding this snippet.

**Comment by timpisti** [comment]
Great, thank you
