### ISSUE TITLE
Slideout visible at the tops of clicked link

### ISSUE THREAD

**Issue by almcaffee** [Mango/slideout#42]
Good Afternoon,

I am trying to implement slideout in a site but it seems to show the nav div on the next page. You can see and example here: http://abatapsendowment.org/mobile-index-test.html. I am not sure what the issue is as it worked fine until about two hours ago when I changed something. Any help would be greatly appreciated. Thanks

Edit: this issue only happens when i click on an internal link from the slideout. Seems like its not toggling of once a link is clicked.

Edit#2: I am new to Github so please let me know if this is not the right place to ask a question like this.

**Comment by pazguille** [comment]
Hi @almcaffee!

You should remove the following scripts/css from your site:

```html
<script src="slideout/test/test.js"></script> 
```
and

```html
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/mocha/1.13.0/mocha.min.css">
<link rel="stylesheet" href="slideout/test/test.css">
```

Also, you should update the following snippet:
```html
<script>
      window.onload = function() {
        document.querySelector('.js-slideout-toggle').addEventListener('click', function() {
          slideout.toggle();
        });

        document.querySelector('#menu').addEventListener('click', function(eve) {
          if (eve.target.nodeName === 'A') { slideout.close(); }
        });
      };
</script>
```

:)
