### ISSUE TITLE
Internet Explorer 10+ throws errors when moving mouse

### ISSUE THREAD

**Issue by johnbacon** [Mango/slideout#43]
On the Slideout demo page, moving the mouse in IE10+ throws the following error over and over again:

```console
SCRIPT5007: Unable to get property '0' of undefined or null reference 
slideout, line 186 character 3494 
```

and highlights the following minified JavaScript as the culprit:
```javascript
var n=t.touches[0].clientX-e._startOffsetX;
```

It appears line 193 of the unminified slideout.js is the issue:
```javascript
var dif_x = eve.touches[0].clientX - self._startOffsetX;
```

**Comment by johnbacon** [comment]
This can be "fixed" by checking for the presence of eve.touches where it is called. For instance:

```javascript
if (typeof eve.touches === 'undefined') { return; }
```

Though I'm sure there's a better way.

**Comment by pazguille** [comment]
#50
