### ISSUE TITLE
Question: Are there any suggestions for using slideout with a fixed header?

### ISSUE THREAD

**Issue by babsonmatt** [Mango/slideout#44]
Or any other fixed content for that matter? Much appreciated!

**Comment by danzajdband** [comment]
panel.getmango.com (the original purpose for slideout.js) uses it along with a fixed header. Maybe @pazguille can help you if you have an issue but it should work as expected.

**Comment by dahlskebank** [comment]
@babsonmatt: I am currently implementing slideout in my WordPress framework. This is the sexiest thing I've seen since Photoswipe. I use several fixed elements, the trick is to create a div-wrapper for non-fixed content, and keep all fixed content outside of that wrapper.

Site below has 1 fixed element (menu button). This was done only for testing purposes, so it is only testable via mobile.
http://floconsulting.nyedesign.no/

Usually I have fixed navbar, 'back-to-top-button', and cookie notice, all this is working perfectly while working locally.

**Comment by jontayesp** [comment]
:+1: 

I'm having trouble with fixed content as well. Any content marked "fixed" (and inside the main panel) will revert to "absolute" position after opening/closing the slideout.

**Comment by pazguille** [comment]
Could you share your code? I created some examples and all works fine for me.

**Comment by jontayesp** [comment]
Sure, I'll post an example tonight.

**Comment by dahlskebank** [comment]
For anyone interested I have implemented this in my WordPress framework and testing it here:

http://zondo.nyedesign.no/

Fixed header, fixed cookie notice, fixed back-to-top button. Working like a charm. No time to paste any code today, but it is as simple as keeping the fixed elements outside of the slideout-panel. Logistically I have elements fixed to top before the panel, elements fixed to bottom after.

This only available to test via mobile, as I use different menu system for desktop.

**Comment by pazguille** [comment]
@dahlskebank awesome! :)

**Comment by jontayesp** [comment]
@dahlskebank So yes, I can use a fixed component outside of the main panel. But I'm trying to include the fixed component inside of the main panel, so that it slides to the right when the slideout is opened. When the slideout is closed, I expect it to revert to its fixed position. 

So what I see right now is the fixed component sliding to the right when opening, sliding to the left when closing (so far so good).. and now the component's position is "absolute", so it doesn't remain fixed on the screen when I scroll up/down. I'll show this later on fiddle or whatever.

Maybe what I am describing isn't supported?

**Comment by dahlskebank** [comment]
@jontayesp: I remember a similar problem with Scotch Panels, see example below if that is the desired effect you are looking for.

http://codepen.io/ncerminara/pen/rtesj

Although I don't know the solution, I know they found a workaround for it with Scotch Panels. I believe the same can be used for Mango Slideout?

**Comment by mahnunchik** [comment]
+1

**Comment by pazguille** [comment]
Hi guys!

I've made an example with a fixed element. I've used CSS and the slideout's events:`beforeopen` and `beforeclose`.

Demo: http://codepen.io/anon/pen/YXpRBX

**Comment by jontayesp** [comment]
That is close to what I am looking for. But I made two small changes to show what I wanted:
 - The fixed box moved inside the "main" panel.
 - The fixed box toggles the slideout when clicked.

http://codepen.io/anon/pen/xGRmmV

But this doesn't work well when the user scrolls down, and then toggles the slideout. I guess I am wondering if fixed content was supported inside the main panel.

**Comment by monecchi** [comment]
@jontayesp Awesome wordpress implementation! Would you mind to share your wordpress menu class along with the slideout.js enhancements? That would be incredibly helpful as I'm not a dev. I've got a theme which has its own slide menu stuff, but it is sluggish, so I'm planning to get rid of it in favor of slideout.js. I can do some tricks with php but not develop all that stuff from the ground up. Thanks in advance.

**Comment by pazguille** [comment]
Info: https://code.google.com/p/chromium/issues/detail?id=20574
So, we should use fixed elements outside from main panel.
Demo: http://codepen.io/anon/pen/NqJGBp

**Comment by jontayesp** [comment]
So fixed content is not currently supported inside the main panel. I'm curious if other options are being researched by @pazguille or @impronunciable? 

IMHO this is an important use-case that should be supported. The goal being to keep the "hamburger" toggle visible on top when scrolling, but still be able to "slide" with the panel when triggered.

Even the landing page https://mango.github.io/slideout/ would benefit from this. There is no way to open the slide-out once you scroll down.

Maybe there are other options such as using absolute position and then moving the element independently. I'm not sure if something like that could be supported by the framework.

**Comment by jontayesp** [comment]
@monecchi I didn't create anything for wordpress, just using the existing slideoutjs landing page for my examples: https://github.com/Mango/slideout/tree/gh-pages.

**Comment by enjoyiacm** [comment]
Question: how to make non scroll to top content (demo: http://codepen.io/anon/pen/NqJGBp) after click humburger for close menu?!

**Comment by slzr** [comment]
i had the same problem, and searching why can't use fixed elements inside de `mainContent` element i see [this](http://stackoverflow.com/questions/15194313/webkit-css-transform3d-position-fixed-issue), but seeing the [solution](http://codepen.io/anon/pen/NqJGBp) of @pazguille, i realize it doesn't work like expected when i use touch events, like swipe to open menu #146, so i implemented the `translate` event to fix this little bug.
http://codepen.io/anon/pen/NqJGBp
there is a little flick bug when transition ends, but i have no idea how to fix it, and i don't know if this is the best solution, but just works for me

**Comment by SuperAL** [comment]
Using slidebars.js as a replacement...

**Comment by AdityaAnand1** [comment]
@slzr Did you end up finding a solution for that flicking?

I ended up here after googling for a fix for this weird animation bug for slideout. Uhhh, why is boostrap so nosey?
