### ISSUE TITLE
Goes back to top if I reveal the menu

### ISSUE THREAD

**Issue by pmtarantino** [Mango/slideout#5]
When I browse the demo pages, after scrolling, if I open the menu, the pages scroll back to the top, losing my position.

Tested on Chrome on Android 5.

**Comment by srikanthegdee** [comment]
Yes, it scrolls back to the top. I am on Android Chrome 4.4

**Comment by miniplus** [comment]
Same thing goes for Mobile Safari on an iPhone 6 plus

**Comment by pazguille** [comment]
Yes, we know this issue. It's happen because we use `overflow:hidden;` on `<html>`  to prevent scrolling the viewport on mobile.

Any idea?

Thanks!

**Comment by pazguille** [comment]
I fix it adding a wrapper element. Then I set the overflow property to `hidden` on this wrapper instead of `<html>` to prevent scrolling.

```css
.slideout-open .slideout-panel-container {
  overflow: hidden;
}
```

```html
<div class="slideout-panel-container">
  <main id="panel class="slideout-panel">
    <header>
      <h2>Panel</h2>
    </header>
  </main>
</div>
```

**Comment by babsonmatt** [comment]
The above fix prevents the scroll to the top, however the menu is no longer visible (since it's at the top).

**Comment by pazguille** [comment]
@babsonmatt 
I think we can fix it with CSS.

I have created a new branch: `fix-back-to-top-5`. Could you help me to test it on your browsers/devices? Just go to this branch and open the file test/index.html.

Thanks!

**Comment by babsonmatt** [comment]
@pazguille works great on chrome dev ( 42.0.2311.15 dev-m (64-bit) ) and firefox 36!

**Comment by pazguille** [comment]
Hi,

I have found a better way to fix it:

1. Remove width and height 100% from `html`.
2. Add `overflow:hidden` to `.slideout-panel` when the slideout is opened.

Could you help me to test it on your devices? Just go to the branch `fix-back-to-top-5` and open the file test/index.html.

:)

**Comment by pazguille** [comment]
#21

**Comment by 2GarinRus** [comment]
Hi,
If i use jQuery library then panel scrolls to the top. Without jQuery it works fine.
