### ISSUE TITLE
Question: Is there a way to destroy it?

### ISSUE THREAD

**Issue by 78doog** [Mango/slideout#55]
Is there a slideout.destroy(); or similar? I'm looking to use it with enquire.js and initiate 2 variations at different breakpoints on the same elements. When I leave the breakpoints I would like to destroy it, before I start a new instance. Thanks

**Comment by pazguille** [comment]
Not yet. But we will consider to add this option in future versions.

**Comment by darfink** [comment]
I'd really appreciate this feature as well

**Comment by janwidmer** [comment]
I'd really appreciate this feature as well
