### ISSUE TITLE
Opening slideout scrolls page to the top

### ISSUE THREAD

**Issue by aviemet** [Mango/slideout#56]
Had a strange bug where every time I opened the slideout, the page jumped to the top on mobile view. I tracked it down to the overflow-x property being set to hidden. Finally fixed it by giving `html` and `body` the `display: inline-table` property. Not sure if this was purely due to the floated elements I have on the page for this project or if anyone else experienced it.

**Comment by pazguille** [comment]
Hi @aviemetI

We fixed this issue: #5 

You should:

- Remove width and height 100% from `html`.
- Add overflow:hidden to `.slideout-panel` when the slideout is opened.
