### ISSUE TITLE
reset panel when it is opened and your resize window

### ISSUE THREAD

**Issue by nicmare** [Mango/slideout#57]
ok. this is very special now but it can happen on desktop. because i use mediaqueries to just have the slideout menu on mobile devices:
1. resize window down to mobile view so that slideout menu appears. open it
2. now resize back to desktop size

as you can now see the panel still have that translate3d property although the slideout menu is hidden because of the mediaqueries. this looks strange now. do you have any idea how to handle that case properly?

**Comment by pazguille** [comment]
You can try something like this:

```js
window.addEventListener('resize', function() {
  slideout.close()
});
```

**Comment by nicmare** [comment]
oh yes. this does the trick. thank you very much. i like easy solutions :)
