### ISSUE TITLE
prevent touch gesture when scrolling within a div

### ISSUE THREAD

**Issue by nicmare** [Mango/slideout#58]
when you have a div with overflow hidden and you want to scroll on x axis, your slideout.js code gets fired. so scrolling back is not possible because everytime the menu opens. any idea?

**Comment by garygreen** [comment]
PR #10 is a pretty nice and simple fix for this. I've forked slideout and it works perfectly with the `grabWidth: 40` option

**Comment by garygreen** [comment]
I think it would be nice to have a `beforeOpen()` callback built in, where you can `return false` to cancel opening of the menu. That way you can add custom logic to decide if the menu should be allowed to open at that point. For instance, disable opening if you was scrolling inside a certain div, etc. Could be useful in this situation.

**Comment by Charpeni** [comment]
Hi,

I'm currently working on a project and one of the modules is a map, the horizontal navigation inside the map is problematic with this slideout.

I updated the slideout.js to add a condition to prevent unwanted opening.

When adds the CSS class "no-slidable" on one of the panel elements the touch is disabled, the name of this class can be defined at initialization.

What do you think guys? I will make a pull request when I have time.

**Comment by nicmare** [comment]
very good idea. thats the way i like to use it in the plugin

**Comment by pazguille** [comment]
#210 https://github.com/Mango/slideout#data-slideout-ignore-attribute
