### ISSUE TITLE
Building on windows

### ISSUE THREAD

**Issue by garygreen** [Mango/slideout#60]
Get an issue when doing `npm install` and building. Anyone else managed to build slideout on windows, or is it not supported?

![error slideout](https://cloud.githubusercontent.com/assets/1702638/7157776/c751a94a-e36a-11e4-955b-554468bdfadd.png)

**Comment by garygreen** [comment]
It's `jsdom` causing the issue. Doesn't appear it's even needed if you want to simply `npm run dist`

**Comment by pazguille** [comment]
I don't use windows. But, it should work.

**Comment by danzajdband** [comment]
@garygreen It has to do with contextify. Please check out their wiki section about installing using windows. https://github.com/brianmcd/contextify/wiki/Windows-Installation-Guide If there is something we can do for Slideout to make it work let us know.

**Comment by garygreen** [comment]
I'm not sure what the jsdom is actually used for in slideout, is it during the testing? I've just seen on the internet that jsdom is a bit of a nightmare to get installed / working on windows, maybe another package could be used in slideout like, cheerio.js?

**Comment by pazguille** [comment]
Yes, we are using jsdom to run tests on Travis CI.

**Comment by pazguille** [comment]
Anyone with the same issue who can help.
