### ISSUE TITLE
sidebar content load issue

### ISSUE THREAD

**Issue by cesarGimenez** [Mango/slideout#62]
In my site (http://mdqmap.com/test.html) when I click on a marker that have a long dinamic content the sidebar not show all the first time IN MOBILE (Chrome Android 4.4.2), I have to close the sidebar and open it again to render all the content. Is this an issue? thanks!

**Comment by pazguille** [comment]
Hi @cesarGimenez,

I don't have an Android device to test it. It looks like an implementation issue, to me.

You could try the following:

```js
  ...

  info.innerHTML = content;
  setTimeout(function() {
    // open sidebar
    if (!(slideout.isOpen())){    
      slideout.open();
    }
  }, 100);
 
  ...
```

**Comment by cesarGimenez** [comment]
thank you so much @pazguille! but still not working. Giving a closer look it seems like when you click on a marker, the height of . slideout-menu get a fixed px, then when you close and open again get the 100% of the viewport height... you can see this with chrome emulator..

**Comment by pazguille** [comment]
Ok. I see you are using position `absolute` on `#map` element.

If I change it for `fixed` it works fine for me.

```css
#map {
  position: fixed;
  top: 0px;
  right: 0px;
  left: 0px;
  bottom: 0px;
}
```

**Comment by cesarGimenez** [comment]
yes! that fix the problem. Thank you so much for your help. Great plugin, I love it!

**Comment by pazguille** [comment]
:)
