### ISSUE TITLE
IE9

### ISSUE THREAD

**Issue by dc34** [Mango/slideout#64]
Hi, love this menu and works fine on everything apart from ie9 and lower is there any fix for this or any way round it thanks

**Comment by pazguille** [comment]
We'll work to fix that (#8)

The slideout should use `left` property instead of `transforms`.

**Comment by dazski31** [comment]
Hi, 
Loving this menu but it still seems buggy in IE9. 
Did you manage to come up with any IE fixes?

Thanks

**Comment by devonmather** [comment]
Is there any update on IE 9 support?

**Comment by Mouvedia** [comment]
@devonmather #122
