### ISSUE TITLE
Open from right side is broken

### ISSUE THREAD

**Issue by montogeek** [Mango/slideout#70]
Hi!

I just update the new version and the new option `side: 'right'` is not working. Screenshot:

![screen shot 2015-05-04 at 08 59 29](https://cloud.githubusercontent.com/assets/1002461/7454715/f7f961ac-f23b-11e4-8b24-025ed6b5132a.png)

Code:
```javascript
var slideout = new Slideout({
  'panel': document.getElementById('content'),
  'menu': document.getElementById('menu'),
  'side': 'right'
});
```

Looks like some CSS is missing

**Comment by pazguille** [comment]
You should update your CSS. Try this:

```css
.slideout-menu { left: auto; }
```

I'm going to add this on the README (#69)

**Comment by montogeek** [comment]
Thanks! But I think that is not a good idea to manually update the CSS for each side.

**Comment by pazguille** [comment]
Maybe, we should and a new class dynamically: `.slideout-menu-left` or `.slideout-menu-right`

**Comment by erichonkanen** [comment]
new to this lib and had same issue, adding css fixed for now...

another issue is how can I have the panel width always be say 90% instead of fixed pixel padding?

**Comment by tatze** [comment]
Currently you cant as the percental values are transformed to px (parseInt and appended px) and further calculations are done with this. But I 2nd that wish and call it a feature request. :)

**Comment by erichonkanen** [comment]
@tatze yes it'd be nice... however I was able to achieve getting it to the right width by doing some simple js calculations and setting it manually
