### ISSUE TITLE
since 0.1.8 "exports is not defined"

### ISSUE THREAD

**Issue by nicmare** [Mango/slideout#71]
since this version slideout.js has stopped working for me. i get the js error "exports is not defined". version 0.1.6 worked fine

**Comment by pazguille** [comment]
I can't reproduce this error. How you are using it? Could you share your code? Thanks

**Comment by nicmare** [comment]
it has somehow to do with emits library. but i am not familiar with it:
http://91.65.248.220/sbc/ (pw: user)

**Comment by pazguille** [comment]
Are you using bower?

**Comment by nicmare** [comment]
yes (and roots sage)

**Comment by pazguille** [comment]
I have made a new version (v0.1.9) and it should work fine. Please, let me know.

**Comment by nicmare** [comment]
awesome! this works now. thank you very much for your quick response

**Comment by pazguille** [comment]
Thank you! Enjoy :)
