### ISSUE TITLE
Fixed header in #panel div 

### ISSUE THREAD

**Issue by ZRdesign** [Mango/slideout#75]
I was really wondering how awesome would  it be to have a fixed header in the #panel div.
I made a little demo by the full example. Unfortunately, if I scroll down in the panel and open the slideout menu after that, the fixed header disappears.
Here is a fiddle about the problem:
https://jsfiddle.net/ZRdesign/v4LbssjL/2/

**Comment by mahnunchik** [comment]
Hi,

I've faced with the same problem.

What do you think how problem with `fixed` header can be solved?

**Comment by ZRdesign** [comment]
I used another plugin for solving this.
http://plugins.adchsm.me/slidebars/
They have good solution for this mentioned here: http://plugins.adchsm.me/slidebars/issues/fixed-position.php

**Comment by pazguille** [comment]
#44
