### ISSUE TITLE
Add a classname dynamically: .slideout-menu-left or .slideout-menu-right

### ISSUE THREAD

**Issue by pazguille** [Mango/slideout#78]

**Comment by peucaio** [comment]
Is this already working @pazguille ? Would be just what I need for a website with 2 menus.

**Comment by opensas** [comment]
Could anybody provide a working example of fiddle or similar? it would also be fine adding it to the FAQs

**Comment by xstortionist** [comment]
@opensas 

Here is a working example of left and right menu.

http://codepen.io/xstortionist/pen/GordGp

**Comment by dcrck** [comment]
@xstortionist Have you tested your codepen in Chrome with device mode set to iPhone 6? It seems both menu's (left & right) become visible.

**Comment by xstortionist** [comment]
@dcrck not sure to be honest, I ended up making my own custom off-canvas menu.

**Comment by matheusjardimb** [comment]
+1 Wanna use this feature too
