### ISSUE TITLE
about. slideout.js

### ISSUE THREAD

**Issue by btt3rfly** [Mango/slideout#79]
https://mango.github.io/slideout/

hi, im using tumblr and dropbox,where can i install the files to make the code for this work,and what should write to redirect the code to the files? thanks, btt3rfly.com

**Comment by pazguille** [comment]
You should download the slideout files (js and css) and add into your HTML => https://github.com/Mango/slideout#full-example

Then, you can read the Usage section documentation => https://github.com/Mango/slideout#usage
