### ISSUE TITLE
The browser doesn't support CSS transform.

### ISSUE THREAD

**Issue by pazguille** [Mango/slideout#8]
If the browser doesn't support CSS `transform`, we should use `left` property.

**Comment by dc34** [comment]
is there anywhere I can download the correct code that will allow ie9 to work please this is my first attempt at inserting anything like this and was so pleased until I saw IE9

**Comment by dazski31** [comment]
I'm in the same boat as dc34, love this menu but need an IE9 fix? anyone?

**Comment by CreepyGnome** [comment]
any status on this supporting IE9?

**Comment by CreepyGnome** [comment]
many Transforms are supported in IE9, it just doesn't support 3D translates. I am not sure why slideout is using translate3d when it doesn't need the z axis. However in my copy I just replaced the two translate3d with translate and the slide out works on IE9 now.

**Comment by dc34** [comment]
Hi, can you please tell me on which css and which line you changed the translate3d to translate as I would like to try this thanks

**Comment by dc34** [comment]
as I have translate3d in the js and css

**Comment by CreepyGnome** [comment]
@dc34 I went ahead and created my own fork, and I have provided the changes in [pull request. #121](https://github.com/Mango/slideout/pull/121). Feel free to use my [IE9-Support branch](https://github.com/CreepyGnome/slideout/tree/IE9-Support) until Mango can review and decide if IE9 support is a feature they like the way I implemented it.

**Comment by jonscottclark** [comment]
translate3d is probably used for acceleration: https://aerotwist.com/blog/on-translate3d-and-layer-creation-hacks/

Would love it if something more future-friendly like `will-change: transform;` could be applied to the sliding element (see https://developer.mozilla.org/en-US/docs/Web/CSS/will-change)

Thanks for the work on this @CreepyGnome, would love to see the PR merged.

**Comment by pazguille** [comment]
https://github.com/Mango/slideout/commit/fbb35b172a0a94b3e58eb5483a14b60bacd84248
