### ISSUE TITLE
Keep menu element hidden until slide out?

### ISSUE THREAD

**Issue by maoxiong** [Mango/slideout#80]
I have an issue where my page is quite big (so takes a while to load up all the images) - during which time the menu bar is displayed at the top of the page - until the onload fires and hides it.

I thought I could get around this by setting the "display" property of the #menu as none and turn it on when the setup JS is called, however if you do this, swipe stops working (though the menu click still works).

Is this a bug - or is there a workaround for this? (I tried using jQuery to set the display:block as pageReady, but still same problem...)

**Comment by pazguille** [comment]
You should add a classname to your `#menu` element.

```html
<nav id="menu" class="menu">
  <header>
    <h2>Menu</h2>
  </header>
</nav>
```

```css
.menu {
  display:none;
}
```

Demo: http://codepen.io/anon/pen/EjgzKm

**Comment by maoxiong** [comment]
Hi Paul - Genius! :)
