### ISSUE TITLE
Having two side-menus on the same page, one left and one right?

### ISSUE THREAD

**Issue by peucaio** [Mango/slideout#89]
Sorry if this was already asked, I couldn't find it.
Is it possible and how it can be done?

**Comment by orangebook** [comment]
hi ,i had implement it ,there is demo on it,click it by  this ul  http://www.cnblogs.com/orangebook/p/4627736.html

**Comment by peucaio** [comment]
Hi @orangebook, I tried to find where to click, but couldn't.
Where exactly I can activate it?

Anyway, as the project needed to be delivered, I had to found an alternative and ended up using Sidr, another plugin for making side menus.

**Comment by pazguille** [comment]
#78
