### ISSUE TITLE
In IE10+ element that are position fixed inside of main do not shift with transform3d

### ISSUE THREAD

**Issue by ankurp** [Mango/slideout#9]
Fix is to use left instead of transform3d property applied on main tag.
https://connect.microsoft.com/IE/feedback/details/806517/ie11-tramsform3d-and-position-fixed-problem

**Comment by danzajdband** [comment]
I think this is covered by https://github.com/Mango/slideout/issues/8

**Comment by pazguille** [comment]
This issue is happening in IE10+ and the issue #8 is in -IE9.

**Comment by pazguille** [comment]
I've made an example with a fixed element. I've used CSS and the slideout's events: `beforeopen` and `beforeclose`.

Demo: http://codepen.io/anon/pen/YXpRBX

**Comment by eduxavier** [comment]
It doesn't work on kindle fire. It worked on chrome at my desktop

*Eduardo Xavier*
Bilbo - Sistemas de Informação para apoiar negócios de venda consignada


http://www.bilbo.com.br

21-98624-0892
21-3942-5088
22-4105-0311 (Nova Friburgo)

2015-07-23 16:54 GMT-03:00 Guille Paz <notifications@github.com>:
