### ISSUE TITLE
Cleanup function

### ISSUE THREAD

**Issue by g-p-g** [Mango/slideout#90]
I'm testing slideout with React and I'm missing a way to properly clean up the event listeners and properties set by slideout when it's instantiated. Have you used it with React and how did you handle this in componentWillUnmount? A cleanup function would be good for handling that.

Maybe it's a non-issue for most use cases where the component that keeps this is never unmounted.

**Comment by danzajdband** [comment]
I'm not sure if I get your question. If you want to remove event listeners you can use the `off` method (https://github.com/Mango/slideout#slideoutoffevent-listener). For example:

```
// First
slideout.on('open', myFunction);

// Later
slideout.off('open', myFunction);
```

**Comment by g-p-g** [comment]
Right, that's not what I was after so let me try to clarify. An example of using slideout with react can be seen at: https://github.com/zier/starter-react-slideout/blob/master/app.js

You will notice that slideout is instantiated at componentDidMount, but the event listeners it creates when that is done are never removed (that example is not really a good one, but it helps in understanding the issue I'm pointing out here). A cleanup function would undo everything that `new Slideout(...)` at line 8 in that example does.

**Comment by danzajdband** [comment]
Gotcha. It relates to #55 and we plan to add the feature. Are you agree to close this issue since #55 will fix it or am I missing something else?

**Comment by g-p-g** [comment]
Indeed, looks like to be the same issue. My bad for missing it, searched for the wrong terms.

**Comment by danzajdband** [comment]
Thanks for reporting.
