### ISSUE TITLE
Page scrolls to Top automatically. How to stop it?

### ISSUE THREAD

**Issue by aslamdoctor** [Mango/slideout#96]
E.g. I have used anchor links in my slideout menu that just scrolls the same page to its various sections. In that situation, if I click on any link under slideout menu, it scrolls the page to that position by keeing the menu open. And when I close the menu, the page scrolls back to top. Is there any way to do any one of below ?
1. Close the menu immediately when clicked on any link under the menu and scroll the page to it's anchor tag.
2. Keep the menu opened as it is right now, but also keep the scrolled position of the page and do not scroll to top when menu is closed.

This can be checked here http://candelisapeople.com.gridhosted.co.uk/

Thank You

**Comment by danzajdband** [comment]
Maybe this can help you #5

**Comment by aslamdoctor** [comment]
I tried that, it is not working. You can test on the same link
http://candelisapeople.com.gridhosted.co.uk/

**Comment by aslamdoctor** [comment]
ignore last message, this has been fixed now :) thank you

**Comment by wesleyfsmith** [comment]
Mind letting me know how you fixed this? I'm having the exact same problem.

**Comment by wesleyfsmith** [comment]
I was able to fix it by following the advice in #5 and removing width: 100%; and height: 100%; from my container.

**Comment by ManishaDere** [comment]
I tried 
$('.link').click(function(e) {
    e.stopPropagation();  //prevent from any parent click handlers that didn't prevent the jump
});
This code prevents from scrolling top after clicking a link.
