### ISSUE TITLE
Slide menu is visible while page is loading

### ISSUE THREAD

**Issue by aslamdoctor** [Mango/slideout#97]
E.g. I have added a slideout menu with black background color, just like there is on https://mango.github.io/slideout/
Each time I open the website on my mobile or try to open the site using Google chrome "Device mode", it loads the Black background menu on top of the page while loading and when the page is completed loading, it then hides the menu. The menu should be hidden from the beginning as per your website
https://mango.github.io/slideout/

The class .slideout-menu has display property to "none", so this is not supposed to happen.

Here is a website where this can be checked where I have implemened.
http://ideal-money.co.uk/

**Comment by aslamdoctor** [comment]
I got it fixed myself. I think this needs to be mentioned somewhere on setup guide.
The nav id="menu" needs to have a class named "menu" and it needs to be display:none by default.
This fixes the slideout menu visibility issue while page loading.

**Comment by Tarek-Adra** [comment]
I switched the main content with the nav

```
<main></main>
<nav></nav>
```
