### ISSUE TITLE
Menu on the right side can hide links if you change padding value

### ISSUE THREAD

**Issue by rafaltrzop** [Mango/slideout#98]
If you set `side` to `right` and change `padding` value to less than default 256px you can get something like this:
![1](https://cloud.githubusercontent.com/assets/2698839/8648137/7a322790-295e-11e5-9075-0fc23ebebf9d.jpg)

On the other hand, if you set it to more than 256px this happens:
![2](https://cloud.githubusercontent.com/assets/2698839/8648145/99b988c4-295e-11e5-844d-f3fea1f6e1d1.jpg)

To repair it you have to also change the value of `width` in slideout-menu class in `bower_components/slideout.js/index.css` (but you shouldn't ever need to touch it) or overwrite it in your CSS app file.

**Comment by pazguille** [comment]
It's fine for me. If you change `padding` value you should update the `width` value in your CSS. You should be able to overwrite any CSS property.
